version: "2"
run:
  go: 1.25.9
  build-tags:
    - WKAFKA
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - decorder
    - durationcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - whitespace
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          failOn: all
          rules: rules.go
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: var-naming
          arguments:
            - - ID
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: should be of the form
      - path: (.+)\.go$
        text: should not use dot imports
      - path: (.+)\.go$
        text: which can be annoying to use
      - path: (.+)\.go$
        text: G102
      - path: (.+)\.go$
        text: G103
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: G115
      - path: (.+)\.go$
        text: G301
      - path: (.+)\.go$
        text: G302
      - path: (.+)\.go$
        text: G304
      - path: (.+)\.go$
        text: G307
      - path: (.+)\.go$
        text: G402
      - path: (.+)\.go$
        text: G404
      - path: (.+)\.go$
        text: SA1019
      - path: (.+)\.go$
        text: SA5001
    paths:
      - configs
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/milvus-io)
      custom-order: true
    gofumpt:
      module-path: github.com/milvus-io
    goimports:
      local-prefixes:
        - github.com/milvus-io
  exclusions:
    generated: lax
    paths:
      - configs
      - third_party$
      - builtin$
      - examples$
