run:
  go: "1.21"
  skip-dirs:
    - bin
    - configs
    - deployments
    - docs
    - scripts
  build-tags:
  - "WKAFKA"
  skip-files:
    - main.go

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - decorder
    - gofmt
    - goimports
    - gosec
    - revive
    - unconvert
    - misspell
    - typecheck
    - durationcheck
    - gci
    - whitespace
    - gofumpt
    - gocritic

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/milvus-io)
    custom-order: true
  gofumpt:
    lang-version: "1.18"
    module-path: github.com/milvus-io
  goimports:
    local-prefixes: github.com/milvus-io
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # Allow list
      - name: context-as-argument
        severity: warning
        disabled: false
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: datarace
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: waitgroup-by-value
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
        arguments:
          - "preserveScope"
      - name: range-val-in-closure
        severity: warning
        disabled: false
      - name: range-val-address
        severity: warning
        disabled: false
      - name: string-of-int
        severity: warning
        disabled: false
  misspell:
    locale: US
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        failOnError: true
        rules: "rules.go"

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    - should have comment
    - should be of the form
    - should not use dot imports
    - which can be annoying to use
    # Binds to all network interfaces
    - G102
    # Use of unsafe calls should be audited
    - G103
    # Errors unhandled
    - G104
    # file/folder Permission
    - G301
    - G302
    # Potential file inclusion via variable
    - G304
    # Deferring unsafe method like *os.File Close
    - G307
    # TLS MinVersion too low
    - G402
    # Use of weak random number generator math/rand
    - G404
    # Unused parameters
    - SA1019
    # defer return errors
    - SA5001

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

service:
  # use the fixed version to not introduce new linters unexpectedly
  golangci-lint-version: 1.55.2
