// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package internalpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/birdwatcher/proto/v2.2/commonpb"
	schemapb "github.com/milvus-io/birdwatcher/proto/v2.2/schemapb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RateType int32

const (
	RateType_DDLCollection RateType = 0
	RateType_DDLPartition  RateType = 1
	RateType_DDLIndex      RateType = 2
	RateType_DDLFlush      RateType = 3
	RateType_DDLCompaction RateType = 4
	RateType_DMLInsert     RateType = 5
	RateType_DMLDelete     RateType = 6
	RateType_DMLBulkLoad   RateType = 7
	RateType_DQLSearch     RateType = 8
	RateType_DQLQuery      RateType = 9
	RateType_DMLUpsert     RateType = 10
)

var RateType_name = map[int32]string{
	0:  "DDLCollection",
	1:  "DDLPartition",
	2:  "DDLIndex",
	3:  "DDLFlush",
	4:  "DDLCompaction",
	5:  "DMLInsert",
	6:  "DMLDelete",
	7:  "DMLBulkLoad",
	8:  "DQLSearch",
	9:  "DQLQuery",
	10: "DMLUpsert",
}

var RateType_value = map[string]int32{
	"DDLCollection": 0,
	"DDLPartition":  1,
	"DDLIndex":      2,
	"DDLFlush":      3,
	"DDLCompaction": 4,
	"DMLInsert":     5,
	"DMLDelete":     6,
	"DMLBulkLoad":   7,
	"DQLSearch":     8,
	"DQLQuery":      9,
	"DMLUpsert":     10,
}

func (x RateType) String() string {
	return proto.EnumName(RateType_name, int32(x))
}

func (RateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

type GetTimeTickChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeTickChannelRequest) Reset()         { *m = GetTimeTickChannelRequest{} }
func (m *GetTimeTickChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeTickChannelRequest) ProtoMessage()    {}
func (*GetTimeTickChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

func (m *GetTimeTickChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeTickChannelRequest.Unmarshal(m, b)
}
func (m *GetTimeTickChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeTickChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeTickChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeTickChannelRequest.Merge(m, src)
}
func (m *GetTimeTickChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeTickChannelRequest.Size(m)
}
func (m *GetTimeTickChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeTickChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeTickChannelRequest proto.InternalMessageInfo

type GetStatisticsChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatisticsChannelRequest) Reset()         { *m = GetStatisticsChannelRequest{} }
func (m *GetStatisticsChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsChannelRequest) ProtoMessage()    {}
func (*GetStatisticsChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}

func (m *GetStatisticsChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsChannelRequest.Unmarshal(m, b)
}
func (m *GetStatisticsChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetStatisticsChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsChannelRequest.Merge(m, src)
}
func (m *GetStatisticsChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsChannelRequest.Size(m)
}
func (m *GetStatisticsChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsChannelRequest proto.InternalMessageInfo

type GetDdChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDdChannelRequest) Reset()         { *m = GetDdChannelRequest{} }
func (m *GetDdChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetDdChannelRequest) ProtoMessage()    {}
func (*GetDdChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{2}
}

func (m *GetDdChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDdChannelRequest.Unmarshal(m, b)
}
func (m *GetDdChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDdChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetDdChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDdChannelRequest.Merge(m, src)
}
func (m *GetDdChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetDdChannelRequest.Size(m)
}
func (m *GetDdChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDdChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDdChannelRequest proto.InternalMessageInfo

type NodeInfo struct {
	Address              *commonpb.Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role                 string            `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{3}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetAddress() *commonpb.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NodeInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type InitParams struct {
	NodeID               int64                    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	StartParams          []*commonpb.KeyValuePair `protobuf:"bytes,2,rep,name=start_params,json=startParams,proto3" json:"start_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *InitParams) Reset()         { *m = InitParams{} }
func (m *InitParams) String() string { return proto.CompactTextString(m) }
func (*InitParams) ProtoMessage()    {}
func (*InitParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{4}
}

func (m *InitParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitParams.Unmarshal(m, b)
}
func (m *InitParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitParams.Marshal(b, m, deterministic)
}
func (m *InitParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitParams.Merge(m, src)
}
func (m *InitParams) XXX_Size() int {
	return xxx_messageInfo_InitParams.Size(m)
}
func (m *InitParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InitParams.DiscardUnknown(m)
}

var xxx_messageInfo_InitParams proto.InternalMessageInfo

func (m *InitParams) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *InitParams) GetStartParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.StartParams
	}
	return nil
}

type StringList struct {
	Values               []string         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Status               *commonpb.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{5}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *StringList) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetStatisticsRequest struct {
	Base *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Not useful for now
	DbID int64 `protobuf:"varint,2,opt,name=dbID,proto3" json:"dbID,omitempty"`
	// The collection you want get statistics
	CollectionID int64 `protobuf:"varint,3,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	// The partitions you want get statistics
	PartitionIDs []int64 `protobuf:"varint,4,rep,packed,name=partitionIDs,proto3" json:"partitionIDs,omitempty"`
	// timestamp of the statistics
	TravelTimestamp      uint64   `protobuf:"varint,5,opt,name=travel_timestamp,json=travelTimestamp,proto3" json:"travel_timestamp,omitempty"`
	GuaranteeTimestamp   uint64   `protobuf:"varint,6,opt,name=guarantee_timestamp,json=guaranteeTimestamp,proto3" json:"guarantee_timestamp,omitempty"`
	TimeoutTimestamp     uint64   `protobuf:"varint,7,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatisticsRequest) Reset()         { *m = GetStatisticsRequest{} }
func (m *GetStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsRequest) ProtoMessage()    {}
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{6}
}

func (m *GetStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsRequest.Unmarshal(m, b)
}
func (m *GetStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsRequest.Merge(m, src)
}
func (m *GetStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsRequest.Size(m)
}
func (m *GetStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsRequest proto.InternalMessageInfo

func (m *GetStatisticsRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetStatisticsRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *GetStatisticsRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *GetStatisticsRequest) GetPartitionIDs() []int64 {
	if m != nil {
		return m.PartitionIDs
	}
	return nil
}

func (m *GetStatisticsRequest) GetTravelTimestamp() uint64 {
	if m != nil {
		return m.TravelTimestamp
	}
	return 0
}

func (m *GetStatisticsRequest) GetGuaranteeTimestamp() uint64 {
	if m != nil {
		return m.GuaranteeTimestamp
	}
	return 0
}

func (m *GetStatisticsRequest) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type GetStatisticsResponse struct {
	Base *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Contain error_code and reason
	Status *commonpb.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Collection statistics data. Contain pairs like {"row_count": "1"}
	Stats                []*commonpb.KeyValuePair `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetStatisticsResponse) Reset()         { *m = GetStatisticsResponse{} }
func (m *GetStatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsResponse) ProtoMessage()    {}
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{7}
}

func (m *GetStatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsResponse.Unmarshal(m, b)
}
func (m *GetStatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsResponse.Marshal(b, m, deterministic)
}
func (m *GetStatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsResponse.Merge(m, src)
}
func (m *GetStatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsResponse.Size(m)
}
func (m *GetStatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsResponse proto.InternalMessageInfo

func (m *GetStatisticsResponse) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetStatisticsResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetStatisticsResponse) GetStats() []*commonpb.KeyValuePair {
	if m != nil {
		return m.Stats
	}
	return nil
}

type CreateAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Alias                string            `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateAliasRequest) Reset()         { *m = CreateAliasRequest{} }
func (m *CreateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliasRequest) ProtoMessage()    {}
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{8}
}

func (m *CreateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasRequest.Unmarshal(m, b)
}
func (m *CreateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasRequest.Marshal(b, m, deterministic)
}
func (m *CreateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasRequest.Merge(m, src)
}
func (m *CreateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliasRequest.Size(m)
}
func (m *CreateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasRequest proto.InternalMessageInfo

func (m *CreateAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateAliasRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type DropAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Alias                string            `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropAliasRequest) Reset()         { *m = DropAliasRequest{} }
func (m *DropAliasRequest) String() string { return proto.CompactTextString(m) }
func (*DropAliasRequest) ProtoMessage()    {}
func (*DropAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{9}
}

func (m *DropAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropAliasRequest.Unmarshal(m, b)
}
func (m *DropAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropAliasRequest.Marshal(b, m, deterministic)
}
func (m *DropAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropAliasRequest.Merge(m, src)
}
func (m *DropAliasRequest) XXX_Size() int {
	return xxx_messageInfo_DropAliasRequest.Size(m)
}
func (m *DropAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropAliasRequest proto.InternalMessageInfo

func (m *DropAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type AlterAliasRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Alias                string            `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AlterAliasRequest) Reset()         { *m = AlterAliasRequest{} }
func (m *AlterAliasRequest) String() string { return proto.CompactTextString(m) }
func (*AlterAliasRequest) ProtoMessage()    {}
func (*AlterAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{10}
}

func (m *AlterAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlterAliasRequest.Unmarshal(m, b)
}
func (m *AlterAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlterAliasRequest.Marshal(b, m, deterministic)
}
func (m *AlterAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlterAliasRequest.Merge(m, src)
}
func (m *AlterAliasRequest) XXX_Size() int {
	return xxx_messageInfo_AlterAliasRequest.Size(m)
}
func (m *AlterAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlterAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlterAliasRequest proto.InternalMessageInfo

func (m *AlterAliasRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AlterAliasRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *AlterAliasRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *AlterAliasRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type CreateIndexRequest struct {
	Base                 *commonpb.MsgBase        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string                   `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string                   `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	FieldName            string                   `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	DbID                 int64                    `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64                    `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	FieldID              int64                    `protobuf:"varint,7,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	ExtraParams          []*commonpb.KeyValuePair `protobuf:"bytes,8,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateIndexRequest) Reset()         { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()    {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{11}
}

func (m *CreateIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndexRequest.Unmarshal(m, b)
}
func (m *CreateIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndexRequest.Marshal(b, m, deterministic)
}
func (m *CreateIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndexRequest.Merge(m, src)
}
func (m *CreateIndexRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIndexRequest.Size(m)
}
func (m *CreateIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndexRequest proto.InternalMessageInfo

func (m *CreateIndexRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateIndexRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateIndexRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateIndexRequest) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *CreateIndexRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreateIndexRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreateIndexRequest) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *CreateIndexRequest) GetExtraParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.ExtraParams
	}
	return nil
}

type SearchRequest struct {
	Base         *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ReqID        int64             `protobuf:"varint,2,opt,name=reqID,proto3" json:"reqID,omitempty"`
	DbID         int64             `protobuf:"varint,3,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID int64             `protobuf:"varint,4,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionIDs []int64           `protobuf:"varint,5,rep,packed,name=partitionIDs,proto3" json:"partitionIDs,omitempty"`
	Dsl          string            `protobuf:"bytes,6,opt,name=dsl,proto3" json:"dsl,omitempty"`
	// serialized `PlaceholderGroup`
	PlaceholderGroup     []byte           `protobuf:"bytes,7,opt,name=placeholder_group,json=placeholderGroup,proto3" json:"placeholder_group,omitempty"`
	DslType              commonpb.DslType `protobuf:"varint,8,opt,name=dsl_type,json=dslType,proto3,enum=milvus.protov2.common.DslType" json:"dsl_type,omitempty"`
	SerializedExprPlan   []byte           `protobuf:"bytes,9,opt,name=serialized_expr_plan,json=serializedExprPlan,proto3" json:"serialized_expr_plan,omitempty"`
	OutputFieldsId       []int64          `protobuf:"varint,10,rep,packed,name=output_fields_id,json=outputFieldsId,proto3" json:"output_fields_id,omitempty"`
	GuaranteeTimestamp   uint64           `protobuf:"varint,12,opt,name=guarantee_timestamp,json=guaranteeTimestamp,proto3" json:"guarantee_timestamp,omitempty"`
	TimeoutTimestamp     uint64           `protobuf:"varint,13,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	Nq                   int64            `protobuf:"varint,14,opt,name=nq,proto3" json:"nq,omitempty"`
	Topk                 int64            `protobuf:"varint,15,opt,name=topk,proto3" json:"topk,omitempty"`
	MetricType           string           `protobuf:"bytes,16,opt,name=metricType,proto3" json:"metricType,omitempty"`
	IgnoreGrowing        bool             `protobuf:"varint,17,opt,name=ignoreGrowing,proto3" json:"ignoreGrowing,omitempty"`
	Username             string           `protobuf:"bytes,18,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{12}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SearchRequest) GetReqID() int64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *SearchRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *SearchRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *SearchRequest) GetPartitionIDs() []int64 {
	if m != nil {
		return m.PartitionIDs
	}
	return nil
}

func (m *SearchRequest) GetDsl() string {
	if m != nil {
		return m.Dsl
	}
	return ""
}

func (m *SearchRequest) GetPlaceholderGroup() []byte {
	if m != nil {
		return m.PlaceholderGroup
	}
	return nil
}

func (m *SearchRequest) GetDslType() commonpb.DslType {
	if m != nil {
		return m.DslType
	}
	return commonpb.DslType_Dsl
}

func (m *SearchRequest) GetSerializedExprPlan() []byte {
	if m != nil {
		return m.SerializedExprPlan
	}
	return nil
}

func (m *SearchRequest) GetOutputFieldsId() []int64 {
	if m != nil {
		return m.OutputFieldsId
	}
	return nil
}

func (m *SearchRequest) GetGuaranteeTimestamp() uint64 {
	if m != nil {
		return m.GuaranteeTimestamp
	}
	return 0
}

func (m *SearchRequest) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func (m *SearchRequest) GetNq() int64 {
	if m != nil {
		return m.Nq
	}
	return 0
}

func (m *SearchRequest) GetTopk() int64 {
	if m != nil {
		return m.Topk
	}
	return 0
}

func (m *SearchRequest) GetMetricType() string {
	if m != nil {
		return m.MetricType
	}
	return ""
}

func (m *SearchRequest) GetIgnoreGrowing() bool {
	if m != nil {
		return m.IgnoreGrowing
	}
	return false
}

func (m *SearchRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SearchResults struct {
	Base                     *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status                   *commonpb.Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ReqID                    int64             `protobuf:"varint,3,opt,name=reqID,proto3" json:"reqID,omitempty"`
	MetricType               string            `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	NumQueries               int64             `protobuf:"varint,5,opt,name=num_queries,json=numQueries,proto3" json:"num_queries,omitempty"`
	TopK                     int64             `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	SealedSegmentIDsSearched []int64           `protobuf:"varint,7,rep,packed,name=sealed_segmentIDs_searched,json=sealedSegmentIDsSearched,proto3" json:"sealed_segmentIDs_searched,omitempty"`
	ChannelIDsSearched       []string          `protobuf:"bytes,8,rep,name=channelIDs_searched,json=channelIDsSearched,proto3" json:"channelIDs_searched,omitempty"`
	GlobalSealedSegmentIDs   []int64           `protobuf:"varint,9,rep,packed,name=global_sealed_segmentIDs,json=globalSealedSegmentIDs,proto3" json:"global_sealed_segmentIDs,omitempty"`
	// schema.SearchResultsData inside
	SlicedBlob     []byte `protobuf:"bytes,10,opt,name=sliced_blob,json=slicedBlob,proto3" json:"sliced_blob,omitempty"`
	SlicedNumCount int64  `protobuf:"varint,11,opt,name=sliced_num_count,json=slicedNumCount,proto3" json:"sliced_num_count,omitempty"`
	SlicedOffset   int64  `protobuf:"varint,12,opt,name=sliced_offset,json=slicedOffset,proto3" json:"sliced_offset,omitempty"`
	// search request cost
	CostAggregation      *CostAggregation `protobuf:"bytes,13,opt,name=costAggregation,proto3" json:"costAggregation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResults) Reset()         { *m = SearchResults{} }
func (m *SearchResults) String() string { return proto.CompactTextString(m) }
func (*SearchResults) ProtoMessage()    {}
func (*SearchResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{13}
}

func (m *SearchResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResults.Unmarshal(m, b)
}
func (m *SearchResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResults.Marshal(b, m, deterministic)
}
func (m *SearchResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResults.Merge(m, src)
}
func (m *SearchResults) XXX_Size() int {
	return xxx_messageInfo_SearchResults.Size(m)
}
func (m *SearchResults) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResults.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResults proto.InternalMessageInfo

func (m *SearchResults) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SearchResults) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchResults) GetReqID() int64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *SearchResults) GetMetricType() string {
	if m != nil {
		return m.MetricType
	}
	return ""
}

func (m *SearchResults) GetNumQueries() int64 {
	if m != nil {
		return m.NumQueries
	}
	return 0
}

func (m *SearchResults) GetTopK() int64 {
	if m != nil {
		return m.TopK
	}
	return 0
}

func (m *SearchResults) GetSealedSegmentIDsSearched() []int64 {
	if m != nil {
		return m.SealedSegmentIDsSearched
	}
	return nil
}

func (m *SearchResults) GetChannelIDsSearched() []string {
	if m != nil {
		return m.ChannelIDsSearched
	}
	return nil
}

func (m *SearchResults) GetGlobalSealedSegmentIDs() []int64 {
	if m != nil {
		return m.GlobalSealedSegmentIDs
	}
	return nil
}

func (m *SearchResults) GetSlicedBlob() []byte {
	if m != nil {
		return m.SlicedBlob
	}
	return nil
}

func (m *SearchResults) GetSlicedNumCount() int64 {
	if m != nil {
		return m.SlicedNumCount
	}
	return 0
}

func (m *SearchResults) GetSlicedOffset() int64 {
	if m != nil {
		return m.SlicedOffset
	}
	return 0
}

func (m *SearchResults) GetCostAggregation() *CostAggregation {
	if m != nil {
		return m.CostAggregation
	}
	return nil
}

type CostAggregation struct {
	ResponseTime         int64    `protobuf:"varint,1,opt,name=responseTime,proto3" json:"responseTime,omitempty"`
	ServiceTime          int64    `protobuf:"varint,2,opt,name=serviceTime,proto3" json:"serviceTime,omitempty"`
	TotalNQ              int64    `protobuf:"varint,3,opt,name=totalNQ,proto3" json:"totalNQ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CostAggregation) Reset()         { *m = CostAggregation{} }
func (m *CostAggregation) String() string { return proto.CompactTextString(m) }
func (*CostAggregation) ProtoMessage()    {}
func (*CostAggregation) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{14}
}

func (m *CostAggregation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CostAggregation.Unmarshal(m, b)
}
func (m *CostAggregation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CostAggregation.Marshal(b, m, deterministic)
}
func (m *CostAggregation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CostAggregation.Merge(m, src)
}
func (m *CostAggregation) XXX_Size() int {
	return xxx_messageInfo_CostAggregation.Size(m)
}
func (m *CostAggregation) XXX_DiscardUnknown() {
	xxx_messageInfo_CostAggregation.DiscardUnknown(m)
}

var xxx_messageInfo_CostAggregation proto.InternalMessageInfo

func (m *CostAggregation) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

func (m *CostAggregation) GetServiceTime() int64 {
	if m != nil {
		return m.ServiceTime
	}
	return 0
}

func (m *CostAggregation) GetTotalNQ() int64 {
	if m != nil {
		return m.TotalNQ
	}
	return 0
}

type RetrieveRequest struct {
	Base                         *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ReqID                        int64             `protobuf:"varint,2,opt,name=reqID,proto3" json:"reqID,omitempty"`
	DbID                         int64             `protobuf:"varint,3,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID                 int64             `protobuf:"varint,4,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionIDs                 []int64           `protobuf:"varint,5,rep,packed,name=partitionIDs,proto3" json:"partitionIDs,omitempty"`
	SerializedExprPlan           []byte            `protobuf:"bytes,6,opt,name=serialized_expr_plan,json=serializedExprPlan,proto3" json:"serialized_expr_plan,omitempty"`
	OutputFieldsId               []int64           `protobuf:"varint,7,rep,packed,name=output_fields_id,json=outputFieldsId,proto3" json:"output_fields_id,omitempty"`
	MvccTimestamp                uint64            `protobuf:"varint,8,opt,name=mvcc_timestamp,json=mvccTimestamp,proto3" json:"mvcc_timestamp,omitempty"`
	GuaranteeTimestamp           uint64            `protobuf:"varint,9,opt,name=guarantee_timestamp,json=guaranteeTimestamp,proto3" json:"guarantee_timestamp,omitempty"`
	TimeoutTimestamp             uint64            `protobuf:"varint,10,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	Limit                        int64             `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	IgnoreGrowing                bool              `protobuf:"varint,12,opt,name=ignoreGrowing,proto3" json:"ignoreGrowing,omitempty"`
	IsCount                      bool              `protobuf:"varint,13,opt,name=is_count,json=isCount,proto3" json:"is_count,omitempty"`
	IterationExtensionReduceRate int64             `protobuf:"varint,14,opt,name=iteration_extension_reduce_rate,json=iterationExtensionReduceRate,proto3" json:"iteration_extension_reduce_rate,omitempty"`
	Username                     string            `protobuf:"bytes,15,opt,name=username,proto3" json:"username,omitempty"`
	ReduceStopForBest            bool              `protobuf:"varint,16,opt,name=reduce_stop_for_best,json=reduceStopForBest,proto3" json:"reduce_stop_for_best,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}          `json:"-"`
	XXX_unrecognized             []byte            `json:"-"`
	XXX_sizecache                int32             `json:"-"`
}

func (m *RetrieveRequest) Reset()         { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()    {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{15}
}

func (m *RetrieveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRequest.Unmarshal(m, b)
}
func (m *RetrieveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRequest.Merge(m, src)
}
func (m *RetrieveRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveRequest.Size(m)
}
func (m *RetrieveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRequest proto.InternalMessageInfo

func (m *RetrieveRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RetrieveRequest) GetReqID() int64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *RetrieveRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *RetrieveRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *RetrieveRequest) GetPartitionIDs() []int64 {
	if m != nil {
		return m.PartitionIDs
	}
	return nil
}

func (m *RetrieveRequest) GetSerializedExprPlan() []byte {
	if m != nil {
		return m.SerializedExprPlan
	}
	return nil
}

func (m *RetrieveRequest) GetOutputFieldsId() []int64 {
	if m != nil {
		return m.OutputFieldsId
	}
	return nil
}

func (m *RetrieveRequest) GetMvccTimestamp() uint64 {
	if m != nil {
		return m.MvccTimestamp
	}
	return 0
}

func (m *RetrieveRequest) GetGuaranteeTimestamp() uint64 {
	if m != nil {
		return m.GuaranteeTimestamp
	}
	return 0
}

func (m *RetrieveRequest) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func (m *RetrieveRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveRequest) GetIgnoreGrowing() bool {
	if m != nil {
		return m.IgnoreGrowing
	}
	return false
}

func (m *RetrieveRequest) GetIsCount() bool {
	if m != nil {
		return m.IsCount
	}
	return false
}

func (m *RetrieveRequest) GetIterationExtensionReduceRate() int64 {
	if m != nil {
		return m.IterationExtensionReduceRate
	}
	return 0
}

func (m *RetrieveRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RetrieveRequest) GetReduceStopForBest() bool {
	if m != nil {
		return m.ReduceStopForBest
	}
	return false
}

type RetrieveResults struct {
	Base                      *commonpb.MsgBase     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Status                    *commonpb.Status      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ReqID                     int64                 `protobuf:"varint,3,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Ids                       *schemapb.IDs         `protobuf:"bytes,4,opt,name=ids,proto3" json:"ids,omitempty"`
	FieldsData                []*schemapb.FieldData `protobuf:"bytes,5,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	SealedSegmentIDsRetrieved []int64               `protobuf:"varint,6,rep,packed,name=sealed_segmentIDs_retrieved,json=sealedSegmentIDsRetrieved,proto3" json:"sealed_segmentIDs_retrieved,omitempty"`
	ChannelIDsRetrieved       []string              `protobuf:"bytes,7,rep,name=channelIDs_retrieved,json=channelIDsRetrieved,proto3" json:"channelIDs_retrieved,omitempty"`
	GlobalSealedSegmentIDs    []int64               `protobuf:"varint,8,rep,packed,name=global_sealed_segmentIDs,json=globalSealedSegmentIDs,proto3" json:"global_sealed_segmentIDs,omitempty"`
	// query request cost
	CostAggregation      *CostAggregation `protobuf:"bytes,13,opt,name=costAggregation,proto3" json:"costAggregation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RetrieveResults) Reset()         { *m = RetrieveResults{} }
func (m *RetrieveResults) String() string { return proto.CompactTextString(m) }
func (*RetrieveResults) ProtoMessage()    {}
func (*RetrieveResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{16}
}

func (m *RetrieveResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveResults.Unmarshal(m, b)
}
func (m *RetrieveResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveResults.Marshal(b, m, deterministic)
}
func (m *RetrieveResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveResults.Merge(m, src)
}
func (m *RetrieveResults) XXX_Size() int {
	return xxx_messageInfo_RetrieveResults.Size(m)
}
func (m *RetrieveResults) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveResults.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveResults proto.InternalMessageInfo

func (m *RetrieveResults) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RetrieveResults) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RetrieveResults) GetReqID() int64 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *RetrieveResults) GetIds() *schemapb.IDs {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *RetrieveResults) GetFieldsData() []*schemapb.FieldData {
	if m != nil {
		return m.FieldsData
	}
	return nil
}

func (m *RetrieveResults) GetSealedSegmentIDsRetrieved() []int64 {
	if m != nil {
		return m.SealedSegmentIDsRetrieved
	}
	return nil
}

func (m *RetrieveResults) GetChannelIDsRetrieved() []string {
	if m != nil {
		return m.ChannelIDsRetrieved
	}
	return nil
}

func (m *RetrieveResults) GetGlobalSealedSegmentIDs() []int64 {
	if m != nil {
		return m.GlobalSealedSegmentIDs
	}
	return nil
}

func (m *RetrieveResults) GetCostAggregation() *CostAggregation {
	if m != nil {
		return m.CostAggregation
	}
	return nil
}

type LoadIndex struct {
	Base                 *commonpb.MsgBase        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SegmentID            int64                    `protobuf:"varint,2,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	FieldName            string                   `protobuf:"bytes,3,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	FieldID              int64                    `protobuf:"varint,4,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	IndexPaths           []string                 `protobuf:"bytes,5,rep,name=index_paths,json=indexPaths,proto3" json:"index_paths,omitempty"`
	IndexParams          []*commonpb.KeyValuePair `protobuf:"bytes,6,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LoadIndex) Reset()         { *m = LoadIndex{} }
func (m *LoadIndex) String() string { return proto.CompactTextString(m) }
func (*LoadIndex) ProtoMessage()    {}
func (*LoadIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{17}
}

func (m *LoadIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadIndex.Unmarshal(m, b)
}
func (m *LoadIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadIndex.Marshal(b, m, deterministic)
}
func (m *LoadIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadIndex.Merge(m, src)
}
func (m *LoadIndex) XXX_Size() int {
	return xxx_messageInfo_LoadIndex.Size(m)
}
func (m *LoadIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadIndex.DiscardUnknown(m)
}

var xxx_messageInfo_LoadIndex proto.InternalMessageInfo

func (m *LoadIndex) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoadIndex) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *LoadIndex) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *LoadIndex) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *LoadIndex) GetIndexPaths() []string {
	if m != nil {
		return m.IndexPaths
	}
	return nil
}

func (m *LoadIndex) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

type IndexStats struct {
	IndexParams          []*commonpb.KeyValuePair `protobuf:"bytes,1,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	NumRelatedSegments   int64                    `protobuf:"varint,2,opt,name=num_related_segments,json=numRelatedSegments,proto3" json:"num_related_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *IndexStats) Reset()         { *m = IndexStats{} }
func (m *IndexStats) String() string { return proto.CompactTextString(m) }
func (*IndexStats) ProtoMessage()    {}
func (*IndexStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{18}
}

func (m *IndexStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexStats.Unmarshal(m, b)
}
func (m *IndexStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexStats.Marshal(b, m, deterministic)
}
func (m *IndexStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexStats.Merge(m, src)
}
func (m *IndexStats) XXX_Size() int {
	return xxx_messageInfo_IndexStats.Size(m)
}
func (m *IndexStats) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexStats.DiscardUnknown(m)
}

var xxx_messageInfo_IndexStats proto.InternalMessageInfo

func (m *IndexStats) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *IndexStats) GetNumRelatedSegments() int64 {
	if m != nil {
		return m.NumRelatedSegments
	}
	return 0
}

type FieldStats struct {
	CollectionID         int64         `protobuf:"varint,1,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	FieldID              int64         `protobuf:"varint,2,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	IndexStats           []*IndexStats `protobuf:"bytes,3,rep,name=index_stats,json=indexStats,proto3" json:"index_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FieldStats) Reset()         { *m = FieldStats{} }
func (m *FieldStats) String() string { return proto.CompactTextString(m) }
func (*FieldStats) ProtoMessage()    {}
func (*FieldStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{19}
}

func (m *FieldStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldStats.Unmarshal(m, b)
}
func (m *FieldStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldStats.Marshal(b, m, deterministic)
}
func (m *FieldStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldStats.Merge(m, src)
}
func (m *FieldStats) XXX_Size() int {
	return xxx_messageInfo_FieldStats.Size(m)
}
func (m *FieldStats) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldStats.DiscardUnknown(m)
}

var xxx_messageInfo_FieldStats proto.InternalMessageInfo

func (m *FieldStats) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *FieldStats) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldStats) GetIndexStats() []*IndexStats {
	if m != nil {
		return m.IndexStats
	}
	return nil
}

type SegmentStats struct {
	SegmentID            int64    `protobuf:"varint,1,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	MemorySize           int64    `protobuf:"varint,2,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	NumRows              int64    `protobuf:"varint,3,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	RecentlyModified     bool     `protobuf:"varint,4,opt,name=recently_modified,json=recentlyModified,proto3" json:"recently_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentStats) Reset()         { *m = SegmentStats{} }
func (m *SegmentStats) String() string { return proto.CompactTextString(m) }
func (*SegmentStats) ProtoMessage()    {}
func (*SegmentStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{20}
}

func (m *SegmentStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentStats.Unmarshal(m, b)
}
func (m *SegmentStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentStats.Marshal(b, m, deterministic)
}
func (m *SegmentStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentStats.Merge(m, src)
}
func (m *SegmentStats) XXX_Size() int {
	return xxx_messageInfo_SegmentStats.Size(m)
}
func (m *SegmentStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentStats.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentStats proto.InternalMessageInfo

func (m *SegmentStats) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentStats) GetMemorySize() int64 {
	if m != nil {
		return m.MemorySize
	}
	return 0
}

func (m *SegmentStats) GetNumRows() int64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *SegmentStats) GetRecentlyModified() bool {
	if m != nil {
		return m.RecentlyModified
	}
	return false
}

type ChannelTimeTickMsg struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ChannelNames         []string          `protobuf:"bytes,2,rep,name=channelNames,proto3" json:"channelNames,omitempty"`
	Timestamps           []uint64          `protobuf:"varint,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	DefaultTimestamp     uint64            `protobuf:"varint,4,opt,name=default_timestamp,json=defaultTimestamp,proto3" json:"default_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelTimeTickMsg) Reset()         { *m = ChannelTimeTickMsg{} }
func (m *ChannelTimeTickMsg) String() string { return proto.CompactTextString(m) }
func (*ChannelTimeTickMsg) ProtoMessage()    {}
func (*ChannelTimeTickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{21}
}

func (m *ChannelTimeTickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelTimeTickMsg.Unmarshal(m, b)
}
func (m *ChannelTimeTickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelTimeTickMsg.Marshal(b, m, deterministic)
}
func (m *ChannelTimeTickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelTimeTickMsg.Merge(m, src)
}
func (m *ChannelTimeTickMsg) XXX_Size() int {
	return xxx_messageInfo_ChannelTimeTickMsg.Size(m)
}
func (m *ChannelTimeTickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelTimeTickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelTimeTickMsg proto.InternalMessageInfo

func (m *ChannelTimeTickMsg) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetChannelNames() []string {
	if m != nil {
		return m.ChannelNames
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *ChannelTimeTickMsg) GetDefaultTimestamp() uint64 {
	if m != nil {
		return m.DefaultTimestamp
	}
	return 0
}

type CredentialInfo struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// encrypted by bcrypt (for higher security level)
	EncryptedPassword string `protobuf:"bytes,2,opt,name=encrypted_password,json=encryptedPassword,proto3" json:"encrypted_password,omitempty"`
	Tenant            string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	IsSuper           bool   `protobuf:"varint,4,opt,name=is_super,json=isSuper,proto3" json:"is_super,omitempty"`
	// encrypted by sha256 (for good performance in cache mapping)
	Sha256Password       string   `protobuf:"bytes,5,opt,name=sha256_password,json=sha256Password,proto3" json:"sha256_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialInfo) Reset()         { *m = CredentialInfo{} }
func (m *CredentialInfo) String() string { return proto.CompactTextString(m) }
func (*CredentialInfo) ProtoMessage()    {}
func (*CredentialInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{22}
}

func (m *CredentialInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialInfo.Unmarshal(m, b)
}
func (m *CredentialInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialInfo.Marshal(b, m, deterministic)
}
func (m *CredentialInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialInfo.Merge(m, src)
}
func (m *CredentialInfo) XXX_Size() int {
	return xxx_messageInfo_CredentialInfo.Size(m)
}
func (m *CredentialInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialInfo proto.InternalMessageInfo

func (m *CredentialInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredentialInfo) GetEncryptedPassword() string {
	if m != nil {
		return m.EncryptedPassword
	}
	return ""
}

func (m *CredentialInfo) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CredentialInfo) GetIsSuper() bool {
	if m != nil {
		return m.IsSuper
	}
	return false
}

func (m *CredentialInfo) GetSha256Password() string {
	if m != nil {
		return m.Sha256Password
	}
	return ""
}

type ListPolicyRequest struct {
	// Not useful for now
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPolicyRequest) Reset()         { *m = ListPolicyRequest{} }
func (m *ListPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*ListPolicyRequest) ProtoMessage()    {}
func (*ListPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{23}
}

func (m *ListPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPolicyRequest.Unmarshal(m, b)
}
func (m *ListPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPolicyRequest.Marshal(b, m, deterministic)
}
func (m *ListPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPolicyRequest.Merge(m, src)
}
func (m *ListPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_ListPolicyRequest.Size(m)
}
func (m *ListPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPolicyRequest proto.InternalMessageInfo

func (m *ListPolicyRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

type ListPolicyResponse struct {
	// Contain error_code and reason
	Status               *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PolicyInfos          []string         `protobuf:"bytes,2,rep,name=policy_infos,json=policyInfos,proto3" json:"policy_infos,omitempty"`
	UserRoles            []string         `protobuf:"bytes,3,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPolicyResponse) Reset()         { *m = ListPolicyResponse{} }
func (m *ListPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*ListPolicyResponse) ProtoMessage()    {}
func (*ListPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{24}
}

func (m *ListPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPolicyResponse.Unmarshal(m, b)
}
func (m *ListPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPolicyResponse.Marshal(b, m, deterministic)
}
func (m *ListPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPolicyResponse.Merge(m, src)
}
func (m *ListPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_ListPolicyResponse.Size(m)
}
func (m *ListPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPolicyResponse proto.InternalMessageInfo

func (m *ListPolicyResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListPolicyResponse) GetPolicyInfos() []string {
	if m != nil {
		return m.PolicyInfos
	}
	return nil
}

func (m *ListPolicyResponse) GetUserRoles() []string {
	if m != nil {
		return m.UserRoles
	}
	return nil
}

type ShowConfigurationsRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pattern              string            `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShowConfigurationsRequest) Reset()         { *m = ShowConfigurationsRequest{} }
func (m *ShowConfigurationsRequest) String() string { return proto.CompactTextString(m) }
func (*ShowConfigurationsRequest) ProtoMessage()    {}
func (*ShowConfigurationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{25}
}

func (m *ShowConfigurationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowConfigurationsRequest.Unmarshal(m, b)
}
func (m *ShowConfigurationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowConfigurationsRequest.Marshal(b, m, deterministic)
}
func (m *ShowConfigurationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowConfigurationsRequest.Merge(m, src)
}
func (m *ShowConfigurationsRequest) XXX_Size() int {
	return xxx_messageInfo_ShowConfigurationsRequest.Size(m)
}
func (m *ShowConfigurationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowConfigurationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowConfigurationsRequest proto.InternalMessageInfo

func (m *ShowConfigurationsRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ShowConfigurationsRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type ShowConfigurationsResponse struct {
	Status               *commonpb.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Configuations        []*commonpb.KeyValuePair `protobuf:"bytes,2,rep,name=configuations,proto3" json:"configuations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ShowConfigurationsResponse) Reset()         { *m = ShowConfigurationsResponse{} }
func (m *ShowConfigurationsResponse) String() string { return proto.CompactTextString(m) }
func (*ShowConfigurationsResponse) ProtoMessage()    {}
func (*ShowConfigurationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{26}
}

func (m *ShowConfigurationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowConfigurationsResponse.Unmarshal(m, b)
}
func (m *ShowConfigurationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowConfigurationsResponse.Marshal(b, m, deterministic)
}
func (m *ShowConfigurationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowConfigurationsResponse.Merge(m, src)
}
func (m *ShowConfigurationsResponse) XXX_Size() int {
	return xxx_messageInfo_ShowConfigurationsResponse.Size(m)
}
func (m *ShowConfigurationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowConfigurationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowConfigurationsResponse proto.InternalMessageInfo

func (m *ShowConfigurationsResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ShowConfigurationsResponse) GetConfiguations() []*commonpb.KeyValuePair {
	if m != nil {
		return m.Configuations
	}
	return nil
}

type Rate struct {
	Rt                   RateType `protobuf:"varint,1,opt,name=rt,proto3,enum=milvus.protov2.internal.RateType" json:"rt,omitempty"`
	R                    float64  `protobuf:"fixed64,2,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{27}
}

func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (m *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(m, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetRt() RateType {
	if m != nil {
		return m.Rt
	}
	return RateType_DDLCollection
}

func (m *Rate) GetR() float64 {
	if m != nil {
		return m.R
	}
	return 0
}

func init() {
	proto.RegisterEnum("milvus.protov2.internal.RateType", RateType_name, RateType_value)
	proto.RegisterType((*GetTimeTickChannelRequest)(nil), "milvus.protov2.internal.GetTimeTickChannelRequest")
	proto.RegisterType((*GetStatisticsChannelRequest)(nil), "milvus.protov2.internal.GetStatisticsChannelRequest")
	proto.RegisterType((*GetDdChannelRequest)(nil), "milvus.protov2.internal.GetDdChannelRequest")
	proto.RegisterType((*NodeInfo)(nil), "milvus.protov2.internal.NodeInfo")
	proto.RegisterType((*InitParams)(nil), "milvus.protov2.internal.InitParams")
	proto.RegisterType((*StringList)(nil), "milvus.protov2.internal.StringList")
	proto.RegisterType((*GetStatisticsRequest)(nil), "milvus.protov2.internal.GetStatisticsRequest")
	proto.RegisterType((*GetStatisticsResponse)(nil), "milvus.protov2.internal.GetStatisticsResponse")
	proto.RegisterType((*CreateAliasRequest)(nil), "milvus.protov2.internal.CreateAliasRequest")
	proto.RegisterType((*DropAliasRequest)(nil), "milvus.protov2.internal.DropAliasRequest")
	proto.RegisterType((*AlterAliasRequest)(nil), "milvus.protov2.internal.AlterAliasRequest")
	proto.RegisterType((*CreateIndexRequest)(nil), "milvus.protov2.internal.CreateIndexRequest")
	proto.RegisterType((*SearchRequest)(nil), "milvus.protov2.internal.SearchRequest")
	proto.RegisterType((*SearchResults)(nil), "milvus.protov2.internal.SearchResults")
	proto.RegisterType((*CostAggregation)(nil), "milvus.protov2.internal.CostAggregation")
	proto.RegisterType((*RetrieveRequest)(nil), "milvus.protov2.internal.RetrieveRequest")
	proto.RegisterType((*RetrieveResults)(nil), "milvus.protov2.internal.RetrieveResults")
	proto.RegisterType((*LoadIndex)(nil), "milvus.protov2.internal.LoadIndex")
	proto.RegisterType((*IndexStats)(nil), "milvus.protov2.internal.IndexStats")
	proto.RegisterType((*FieldStats)(nil), "milvus.protov2.internal.FieldStats")
	proto.RegisterType((*SegmentStats)(nil), "milvus.protov2.internal.SegmentStats")
	proto.RegisterType((*ChannelTimeTickMsg)(nil), "milvus.protov2.internal.ChannelTimeTickMsg")
	proto.RegisterType((*CredentialInfo)(nil), "milvus.protov2.internal.CredentialInfo")
	proto.RegisterType((*ListPolicyRequest)(nil), "milvus.protov2.internal.ListPolicyRequest")
	proto.RegisterType((*ListPolicyResponse)(nil), "milvus.protov2.internal.ListPolicyResponse")
	proto.RegisterType((*ShowConfigurationsRequest)(nil), "milvus.protov2.internal.ShowConfigurationsRequest")
	proto.RegisterType((*ShowConfigurationsResponse)(nil), "milvus.protov2.internal.ShowConfigurationsResponse")
	proto.RegisterType((*Rate)(nil), "milvus.protov2.internal.Rate")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_41f4a519b878ee3b) }

var fileDescriptor_41f4a519b878ee3b = []byte{
	// 1971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x5b, 0x6f, 0x1c, 0x49,
	0x15, 0xa6, 0xe7, 0x3e, 0x67, 0xc6, 0xe3, 0x71, 0xc5, 0x9b, 0xed, 0x38, 0x9b, 0x8d, 0xb7, 0x17,
	0x84, 0xb9, 0x6c, 0xc2, 0x0e, 0x0a, 0xec, 0x4a, 0x08, 0x29, 0x71, 0x27, 0xd6, 0x68, 0x27, 0xc1,
	0xe9, 0x09, 0x08, 0xc1, 0x43, 0xab, 0xa6, 0xbb, 0x3c, 0x2e, 0xa5, 0xbb, 0xab, 0x5d, 0x55, 0xed,
	0xd8, 0x79, 0x05, 0xf1, 0x86, 0xc4, 0x0b, 0xaf, 0xc0, 0x3f, 0xe0, 0x11, 0xed, 0x03, 0x4f, 0xfc,
	0x05, 0xfe, 0x07, 0xff, 0x00, 0xa1, 0xba, 0xf4, 0xdc, 0x7c, 0xd9, 0xb5, 0xad, 0x85, 0xe5, 0xad,
	0xea, 0x3b, 0x5f, 0x9d, 0xaa, 0x3a, 0x75, 0xfa, 0xab, 0x53, 0x0d, 0x3d, 0x9a, 0x49, 0xc2, 0x33,
	0x9c, 0x3c, 0xc8, 0x39, 0x93, 0x0c, 0xbd, 0x9b, 0xd2, 0xe4, 0xb8, 0x10, 0xa6, 0x77, 0x3c, 0x78,
	0x50, 0x9a, 0xb7, 0xba, 0x11, 0x4b, 0x53, 0x96, 0x19, 0xc3, 0x56, 0x57, 0x44, 0x87, 0x24, 0xc5,
	0xa6, 0xe7, 0xdd, 0x85, 0x3b, 0x7b, 0x44, 0xbe, 0xa2, 0x29, 0x79, 0x45, 0xa3, 0xd7, 0xbb, 0x87,
	0x38, 0xcb, 0x48, 0x12, 0x90, 0xa3, 0x82, 0x08, 0xe9, 0xdd, 0x83, 0xbb, 0x7b, 0x44, 0x8e, 0x25,
	0x96, 0x54, 0x48, 0x1a, 0x89, 0x15, 0xf3, 0x3b, 0x70, 0x6b, 0x8f, 0x48, 0x3f, 0x5e, 0x81, 0x7f,
	0x09, 0xad, 0x17, 0x2c, 0x26, 0xc3, 0xec, 0x80, 0xa1, 0x4f, 0xa0, 0x89, 0xe3, 0x98, 0x13, 0x21,
	0x5c, 0x67, 0xdb, 0xd9, 0xe9, 0x0c, 0xde, 0x7f, 0xb0, 0xb2, 0x4a, 0xbb, 0xb6, 0xc7, 0x86, 0x15,
	0x94, 0x74, 0x84, 0xa0, 0xc6, 0x59, 0x42, 0xdc, 0xca, 0xb6, 0xb3, 0xd3, 0x0e, 0x74, 0xdb, 0x4b,
	0x00, 0x86, 0x19, 0x95, 0xfb, 0x98, 0xe3, 0x54, 0xa0, 0xdb, 0xd0, 0xc8, 0xd4, 0x3c, 0xbe, 0x76,
	0x5d, 0x0d, 0x6c, 0x0f, 0x3d, 0x83, 0xae, 0x90, 0x98, 0xcb, 0x30, 0xd7, 0x3c, 0xb7, 0xb2, 0x5d,
	0xdd, 0xe9, 0x0c, 0x3e, 0xbc, 0x60, 0xe2, 0xcf, 0xc8, 0xe9, 0x2f, 0x70, 0x52, 0x90, 0x7d, 0x4c,
	0x79, 0xd0, 0xd1, 0x03, 0x8d, 0x7f, 0xef, 0xd7, 0x00, 0x63, 0xc9, 0x69, 0x36, 0x1d, 0x51, 0x21,
	0xd5, 0x6c, 0xc7, 0x8a, 0xa7, 0x36, 0x52, 0xdd, 0x69, 0x07, 0xb6, 0x87, 0x1e, 0x41, 0x43, 0x48,
	0x2c, 0x0b, 0xa1, 0x57, 0xda, 0x19, 0xdc, 0xbb, 0x60, 0x9e, 0xb1, 0x26, 0x05, 0x96, 0xec, 0xfd,
	0xb5, 0x02, 0x9b, 0x4b, 0xb1, 0xb5, 0xd1, 0x43, 0x03, 0xa8, 0x4d, 0xb0, 0x20, 0x5f, 0x10, 0xae,
	0xe7, 0x62, 0xfa, 0x04, 0x0b, 0x12, 0x68, 0xae, 0x8a, 0x55, 0x3c, 0x19, 0xfa, 0x7a, 0x05, 0xd5,
	0x40, 0xb7, 0x91, 0x07, 0xdd, 0x88, 0x25, 0x09, 0x89, 0x24, 0x65, 0xd9, 0xd0, 0x77, 0xab, 0xda,
	0xb6, 0x84, 0x29, 0x4e, 0x8e, 0xb9, 0xa4, 0xa6, 0x2b, 0xdc, 0xda, 0x76, 0x55, 0x71, 0x16, 0x31,
	0xf4, 0x1d, 0xe8, 0x4b, 0x8e, 0x8f, 0x49, 0x12, 0x4a, 0x9a, 0x12, 0x21, 0x71, 0x9a, 0xbb, 0xf5,
	0x6d, 0x67, 0xa7, 0x16, 0xac, 0x1b, 0xfc, 0x55, 0x09, 0xa3, 0x87, 0x70, 0x6b, 0x5a, 0x60, 0x8e,
	0x33, 0x49, 0xc8, 0x02, 0xbb, 0xa1, 0xd9, 0x68, 0x66, 0x9a, 0x0f, 0xf8, 0x1e, 0x6c, 0x28, 0x1a,
	0x2b, 0xe4, 0x02, 0xbd, 0xa9, 0xe9, 0x7d, 0x6b, 0x98, 0x91, 0xbd, 0xbf, 0x3b, 0xf0, 0xce, 0x4a,
	0xc4, 0x44, 0xce, 0x32, 0x41, 0xae, 0x15, 0xb2, 0xeb, 0x1d, 0x1b, 0xfa, 0x14, 0xea, 0xaa, 0x25,
	0xdc, 0xea, 0x97, 0x4f, 0x2a, 0x33, 0xc2, 0xfb, 0x8b, 0x03, 0x68, 0x97, 0x13, 0x2c, 0xc9, 0xe3,
	0x84, 0xe2, 0x1b, 0x9d, 0xf7, 0xbb, 0xd0, 0x8c, 0x27, 0x61, 0x86, 0xd3, 0xf2, 0xf3, 0x68, 0xc4,
	0x93, 0x17, 0x38, 0x25, 0xe8, 0xdb, 0xb0, 0x3e, 0x3f, 0x60, 0x43, 0xa8, 0x6a, 0x42, 0x6f, 0x0e,
	0x6b, 0xe2, 0x26, 0xd4, 0xb1, 0x5a, 0x85, 0x5b, 0xd3, 0x66, 0xd3, 0xf1, 0x0a, 0xe8, 0xfb, 0x9c,
	0xe5, 0x5f, 0xdd, 0xfa, 0x66, 0xd3, 0x56, 0x17, 0xa7, 0xfd, 0xb3, 0x03, 0x1b, 0x8f, 0x13, 0x49,
	0xf8, 0xd7, 0x36, 0x30, 0xff, 0xa8, 0x94, 0x67, 0x37, 0xcc, 0x62, 0x72, 0xf2, 0xbf, 0x5d, 0xe2,
	0x3d, 0x80, 0x03, 0x4a, 0x92, 0xd8, 0x70, 0xcc, 0x3a, 0xdb, 0x1a, 0xd1, 0xe6, 0x52, 0x0c, 0xea,
	0x97, 0x88, 0x41, 0xe3, 0x1c, 0x31, 0x70, 0xa1, 0xa9, 0x9d, 0x0c, 0x7d, 0xfd, 0x09, 0x56, 0x83,
	0xb2, 0xab, 0x04, 0x95, 0x9c, 0x48, 0x8e, 0x4b, 0x41, 0x6d, 0x5d, 0x41, 0x50, 0xf5, 0x40, 0x2b,
	0xa8, 0xff, 0xaa, 0xc1, 0xda, 0x98, 0x60, 0x1e, 0x1d, 0xde, 0x24, 0x80, 0x9b, 0x50, 0xe7, 0xe4,
	0x68, 0xa6, 0x76, 0xa6, 0x33, 0xdb, 0x75, 0xf5, 0x92, 0x5d, 0xd7, 0xbe, 0x84, 0x04, 0xd6, 0xcf,
	0x91, 0xc0, 0x3e, 0x54, 0x63, 0x91, 0xe8, 0xa0, 0xb5, 0x03, 0xd5, 0x54, 0xc2, 0x95, 0x27, 0x38,
	0x22, 0x87, 0x2c, 0x89, 0x09, 0x0f, 0xa7, 0x9c, 0x15, 0x46, 0xb8, 0xba, 0x41, 0x7f, 0xc1, 0xb0,
	0xa7, 0x70, 0xf4, 0x29, 0xb4, 0x62, 0x91, 0x84, 0xf2, 0x34, 0x27, 0x6e, 0x6b, 0xdb, 0xd9, 0xe9,
	0x5d, 0xb8, 0x51, 0x5f, 0x24, 0xaf, 0x4e, 0x73, 0x12, 0x34, 0x63, 0xd3, 0x40, 0x3f, 0x80, 0x4d,
	0x41, 0x38, 0xc5, 0x09, 0x7d, 0x4b, 0xe2, 0x90, 0x9c, 0xe4, 0x3c, 0xcc, 0x13, 0x9c, 0xb9, 0x6d,
	0x3d, 0x15, 0x9a, 0xdb, 0x9e, 0x9e, 0xe4, 0x7c, 0x3f, 0xc1, 0x19, 0xda, 0x81, 0x3e, 0x2b, 0x64,
	0x5e, 0xc8, 0x50, 0x9f, 0x9e, 0x08, 0x69, 0xec, 0x82, 0xde, 0x53, 0xcf, 0xe0, 0xcf, 0x34, 0x3c,
	0x8c, 0x2f, 0x52, 0xeb, 0xee, 0xd5, 0xd4, 0x7a, 0xed, 0x7c, 0xb5, 0x46, 0x3d, 0xa8, 0x64, 0x47,
	0x6e, 0x4f, 0x47, 0xbc, 0x92, 0x1d, 0xa9, 0xf3, 0x91, 0x2c, 0x7f, 0xed, 0xae, 0x9b, 0xf3, 0x51,
	0x6d, 0xf4, 0x3e, 0x40, 0x4a, 0x24, 0xa7, 0x91, 0xda, 0xab, 0xdb, 0xd7, 0xe1, 0x5d, 0x40, 0xd0,
	0x37, 0x61, 0x8d, 0x4e, 0x33, 0xc6, 0xc9, 0x1e, 0x67, 0x6f, 0x68, 0x36, 0x75, 0x37, 0xb6, 0x9d,
	0x9d, 0x56, 0xb0, 0x0c, 0xa2, 0x2d, 0x68, 0x15, 0x42, 0x15, 0x3a, 0x29, 0x71, 0x91, 0xf6, 0x31,
	0xeb, 0x7b, 0xff, 0x5c, 0xc8, 0x38, 0x51, 0x24, 0x52, 0xfc, 0x37, 0xef, 0x8a, 0x59, 0xa2, 0x56,
	0x17, 0x13, 0xf5, 0x3e, 0x74, 0xcc, 0x16, 0x4d, 0x42, 0xd4, 0xce, 0xec, 0xfa, 0x3e, 0x74, 0xb2,
	0x22, 0x0d, 0x8f, 0x0a, 0xc2, 0x29, 0x11, 0xf6, 0x33, 0x86, 0xac, 0x48, 0x5f, 0x1a, 0x04, 0xdd,
	0x82, 0xba, 0x64, 0x79, 0xf8, 0xda, 0x7e, 0xc5, 0x2a, 0x96, 0x9f, 0xa1, 0x9f, 0xc0, 0x96, 0x20,
	0x38, 0x21, 0x71, 0x28, 0xc8, 0x34, 0x25, 0x99, 0x1c, 0xfa, 0x22, 0x14, 0x7a, 0xeb, 0x24, 0x76,
	0x9b, 0x3a, 0x03, 0x5c, 0xc3, 0x18, 0xcf, 0x08, 0x63, 0x6b, 0x57, 0xb9, 0x10, 0x99, 0x22, 0x6e,
	0x69, 0x58, 0x4b, 0x57, 0x3a, 0x68, 0x6e, 0x9a, 0x0d, 0xf8, 0x04, 0xdc, 0x69, 0xc2, 0x26, 0x38,
	0x09, 0xcf, 0xcc, 0xea, 0xb6, 0xf5, 0x64, 0xb7, 0x8d, 0x7d, 0xbc, 0x32, 0xa5, 0xda, 0x9e, 0x48,
	0x68, 0x44, 0xe2, 0x70, 0x92, 0xb0, 0x89, 0x0b, 0x3a, 0x93, 0xc1, 0x40, 0x4f, 0x12, 0x36, 0x51,
	0x19, 0x6c, 0x09, 0x2a, 0x0c, 0x11, 0x2b, 0x32, 0xe9, 0x76, 0xf4, 0x4e, 0x7b, 0x06, 0x7f, 0x51,
	0xa4, 0xbb, 0x0a, 0x45, 0x1f, 0xc2, 0x9a, 0x65, 0xb2, 0x83, 0x03, 0x41, 0xa4, 0xce, 0xdd, 0x6a,
	0xd0, 0x35, 0xe0, 0xcf, 0x34, 0x86, 0x02, 0x25, 0xab, 0x42, 0x3e, 0x9e, 0x4e, 0x39, 0x99, 0x62,
	0xf5, 0x49, 0xeb, 0x9c, 0xed, 0x0c, 0x76, 0x1e, 0x5c, 0x50, 0x2f, 0x3f, 0xd8, 0x5d, 0xe6, 0x07,
	0xab, 0x0e, 0xbc, 0x23, 0x58, 0x5f, 0xe1, 0x28, 0x1d, 0xe1, 0xb6, 0x1e, 0x51, 0x1f, 0x81, 0x2d,
	0x49, 0x97, 0x30, 0xb4, 0x0d, 0x1d, 0x41, 0xf8, 0x31, 0x8d, 0x0c, 0xc5, 0xe8, 0xd7, 0x22, 0xa4,
	0x34, 0x58, 0x32, 0x89, 0x93, 0x17, 0x2f, 0x6d, 0xd2, 0x94, 0x5d, 0xef, 0x37, 0x75, 0x58, 0x0f,
	0x54, 0x92, 0x90, 0x63, 0xf2, 0xff, 0xa5, 0x9e, 0x17, 0x69, 0x58, 0xe3, 0x4a, 0x1a, 0xd6, 0x3c,
	0x57, 0xc3, 0xbe, 0x05, 0xbd, 0xf4, 0x38, 0x8a, 0x16, 0xf4, 0xa8, 0xa5, 0xf5, 0x68, 0x4d, 0xa1,
	0x5f, 0x58, 0x98, 0xb6, 0xaf, 0x26, 0x75, 0x70, 0x81, 0xd4, 0x6d, 0x42, 0x3d, 0xa1, 0x29, 0x2d,
	0xb3, 0xd4, 0x74, 0xce, 0x8a, 0x57, 0xf7, 0x3c, 0xf1, 0xba, 0x03, 0x2d, 0x2a, 0x6c, 0x92, 0xaf,
	0x69, 0x42, 0x93, 0x0a, 0x93, 0xdd, 0x4f, 0xe1, 0x3e, 0x95, 0x84, 0xeb, 0xf4, 0x0a, 0xc9, 0x89,
	0x24, 0x99, 0x50, 0x2d, 0x4e, 0xe2, 0x22, 0x22, 0x21, 0xc7, 0x92, 0x58, 0x79, 0x7d, 0x6f, 0x46,
	0x7b, 0x5a, 0xb2, 0x02, 0x4d, 0x0a, 0xb0, 0x24, 0x4b, 0xf2, 0xb8, 0xbe, 0x2c, 0x8f, 0xe8, 0x21,
	0x6c, 0x5a, 0x77, 0x42, 0x29, 0xca, 0x01, 0xe3, 0xe1, 0x84, 0x08, 0xa9, 0xa5, 0xb8, 0x15, 0x6c,
	0x18, 0xdb, 0x58, 0xb2, 0xfc, 0x19, 0xe3, 0x4f, 0xd4, 0xd3, 0xee, 0xb7, 0xb5, 0xc5, 0x2c, 0xfc,
	0x9a, 0x28, 0xea, 0xf7, 0xa1, 0x4a, 0x63, 0x53, 0xb0, 0x75, 0x06, 0x5b, 0xab, 0x9e, 0xec, 0x6b,
	0x77, 0xe8, 0x8b, 0x40, 0xd1, 0xd0, 0x63, 0xe8, 0xd8, 0xac, 0x8a, 0xb1, 0xc4, 0x3a, 0x63, 0x3b,
	0x83, 0xed, 0x0b, 0x46, 0xe9, 0x44, 0xf3, 0xb1, 0xc4, 0x81, 0x29, 0xb9, 0x84, 0x6a, 0xa3, 0x9f,
	0xc2, 0xdd, 0xb3, 0x5a, 0xcb, 0x6d, 0x58, 0x62, 0xb7, 0xa1, 0x53, 0xf5, 0xce, 0xaa, 0xd8, 0x96,
	0x71, 0x8b, 0xd1, 0xc7, 0xb0, 0xb9, 0xa0, 0xb6, 0xf3, 0x81, 0x4d, 0x2d, 0xb7, 0x0b, 0x4a, 0x3c,
	0x1f, 0x72, 0x99, 0xde, 0xb6, 0x2e, 0xd5, 0xdb, 0xaf, 0x42, 0xff, 0xfe, 0xed, 0x40, 0x7b, 0xc4,
	0x70, 0xac, 0x8b, 0xe1, 0x6b, 0x25, 0xc0, 0x7b, 0xd0, 0x9e, 0xed, 0xc0, 0x4a, 0xd1, 0x1c, 0x50,
	0xd6, 0x59, 0x3d, 0x6b, 0x8b, 0xe0, 0x85, 0x02, 0x77, 0xa1, 0x50, 0xad, 0x2d, 0x17, 0xaa, 0xf7,
	0xa1, 0x43, 0xd5, 0x92, 0xc2, 0x1c, 0xcb, 0x43, 0xa3, 0x46, 0xed, 0x00, 0x34, 0xb4, 0xaf, 0x10,
	0x55, 0xc9, 0x96, 0x04, 0x5d, 0xc9, 0x36, 0xae, 0x50, 0xc9, 0x5a, 0x37, 0xba, 0x92, 0xfd, 0x9d,
	0x03, 0xa0, 0x37, 0xaf, 0x12, 0xf4, 0xac, 0x5b, 0xe7, 0x7a, 0x6e, 0x95, 0x54, 0xaa, 0x3b, 0x8f,
	0x93, 0x04, 0xcb, 0xf9, 0x19, 0x0b, 0x1b, 0x20, 0x94, 0x15, 0x69, 0x60, 0x4c, 0xf6, 0x7c, 0x85,
	0xf7, 0x07, 0x07, 0x40, 0x27, 0xa9, 0x59, 0xc8, 0xaa, 0x66, 0x3b, 0x97, 0xd7, 0xf9, 0x95, 0xe5,
	0xf0, 0xf9, 0x65, 0xf8, 0x2e, 0x7d, 0xe2, 0xce, 0xd2, 0x64, 0x1e, 0x00, 0x1b, 0x63, 0xdd, 0xf6,
	0xfe, 0xe8, 0x40, 0xd7, 0xae, 0xcf, 0x2c, 0x6a, 0xe9, 0xac, 0x9d, 0xd5, 0xb3, 0xd6, 0xf5, 0x50,
	0xca, 0xf8, 0x69, 0x28, 0xe8, 0xdb, 0xf2, 0x52, 0x04, 0x03, 0x8d, 0xe9, 0x5b, 0xa2, 0x24, 0x52,
	0x07, 0x85, 0xbd, 0x11, 0xe5, 0xa5, 0xa8, 0x02, 0xc1, 0xde, 0x08, 0x25, 0xd3, 0x9c, 0x44, 0x24,
	0x93, 0xc9, 0x69, 0x98, 0xb2, 0x98, 0x1e, 0x50, 0x12, 0xeb, 0x9c, 0x68, 0x05, 0xfd, 0xd2, 0xf0,
	0xdc, 0xe2, 0xde, 0xe7, 0xea, 0xfd, 0x6d, 0x3e, 0xad, 0xf2, 0x77, 0xd7, 0x73, 0x31, 0xbd, 0x56,
	0xf6, 0xaa, 0x30, 0x1b, 0x4f, 0x2a, 0x21, 0xcd, 0x1f, 0xa6, 0x76, 0xb0, 0x84, 0xa9, 0xe2, 0x76,
	0x76, 0x75, 0x98, 0x58, 0xd6, 0x82, 0x05, 0x44, 0xad, 0x3d, 0x26, 0x07, 0xb8, 0x48, 0x16, 0xaf,
	0x98, 0x9a, 0xb9, 0x62, 0xac, 0x61, 0xfe, 0xef, 0xe3, 0x6f, 0x0e, 0xf4, 0x76, 0x39, 0x89, 0x49,
	0x26, 0x29, 0x4e, 0xf4, 0x9f, 0xb5, 0x45, 0x5d, 0x77, 0x56, 0x74, 0xfd, 0x23, 0x40, 0x24, 0x8b,
	0xf8, 0x69, 0xae, 0xb2, 0x28, 0xc7, 0x42, 0xbc, 0x61, 0x3c, 0xb6, 0xcf, 0xcd, 0x8d, 0x99, 0x65,
	0xdf, 0x1a, 0xd0, 0x6d, 0x68, 0x48, 0x92, 0xe1, 0x4c, 0xda, 0x6f, 0xcd, 0xf6, 0xec, 0xe5, 0x24,
	0x8a, 0x9c, 0x70, 0x1b, 0xd5, 0x26, 0x15, 0x63, 0xd5, 0x55, 0x8f, 0x55, 0x71, 0x88, 0x07, 0x8f,
	0x7e, 0x34, 0x77, 0x5f, 0x37, 0x8f, 0x55, 0x03, 0x97, 0xbe, 0xbd, 0x3d, 0xd8, 0x18, 0x51, 0x21,
	0xf7, 0x59, 0x42, 0xa3, 0xd3, 0x1b, 0x14, 0x2e, 0xde, 0xef, 0x1d, 0x40, 0x8b, 0x9e, 0xec, 0xbf,
	0x9f, 0xf9, 0x4d, 0xe2, 0x5c, 0xe5, 0x26, 0xf9, 0x00, 0xba, 0xb9, 0x76, 0x14, 0xd2, 0xec, 0x80,
	0x95, 0x27, 0xd8, 0x31, 0x98, 0x8a, 0xaf, 0x50, 0xcf, 0x6c, 0x15, 0xd0, 0x90, 0xb3, 0x84, 0x98,
	0x03, 0x6c, 0x07, 0x6d, 0x85, 0x04, 0x0a, 0xf0, 0x28, 0xdc, 0x19, 0x1f, 0xb2, 0x37, 0xbb, 0x2c,
	0x3b, 0xa0, 0xd3, 0xc2, 0xdc, 0xbf, 0x37, 0xfa, 0x77, 0xe1, 0x42, 0x33, 0xc7, 0x52, 0x7d, 0x5b,
	0xf6, 0xa4, 0xca, 0xae, 0xf7, 0x27, 0x07, 0xb6, 0xce, 0x9b, 0xeb, 0x66, 0x21, 0x18, 0xc2, 0x5a,
	0x64, 0x1c, 0x1a, 0x7f, 0x57, 0xf9, 0x4f, 0xba, 0x3c, 0xd2, 0xdb, 0x83, 0x9a, 0xae, 0x35, 0x3e,
	0x86, 0x0a, 0x97, 0x7a, 0x15, 0xbd, 0xc1, 0x07, 0x17, 0xea, 0x86, 0xa2, 0xea, 0x67, 0x6e, 0x85,
	0x4b, 0xd4, 0x05, 0x87, 0xeb, 0xfd, 0x3a, 0x81, 0xc3, 0xbf, 0xfb, 0xb9, 0x03, 0xad, 0xd2, 0x8c,
	0x36, 0x60, 0xcd, 0xf7, 0x47, 0xbb, 0x33, 0xed, 0xea, 0x7f, 0x03, 0xf5, 0xa1, 0xeb, 0xfb, 0xa3,
	0xfd, 0xb2, 0xbc, 0xec, 0x3b, 0xa8, 0x0b, 0x2d, 0xdf, 0x1f, 0x69, 0x29, 0xea, 0x57, 0x6c, 0xef,
	0x59, 0x52, 0x88, 0xc3, 0x7e, 0x75, 0xe6, 0x20, 0xcd, 0xb1, 0x71, 0x50, 0x43, 0x6b, 0xd0, 0xf6,
	0x9f, 0x8f, 0x86, 0x99, 0x20, 0x5c, 0xf6, 0xeb, 0xb6, 0xeb, 0x93, 0x84, 0x48, 0xd2, 0x6f, 0xa0,
	0x75, 0xe8, 0xf8, 0xcf, 0x47, 0x4f, 0x8a, 0xe4, 0xb5, 0xba, 0xdd, 0xfa, 0x4d, 0x6d, 0x7f, 0x39,
	0x32, 0xaf, 0x9e, 0x7e, 0x4b, 0xbb, 0x7f, 0x39, 0x52, 0xef, 0xb0, 0xd3, 0x7e, 0xdb, 0x0e, 0xfe,
	0x79, 0xae, 0x7d, 0xc1, 0x93, 0x1f, 0xff, 0xea, 0xd1, 0x94, 0xca, 0xc3, 0x62, 0xa2, 0x22, 0xf6,
	0xd0, 0x6c, 0xfe, 0x23, 0xca, 0x6c, 0xeb, 0x61, 0xb9, 0xfd, 0x87, 0x3a, 0x1e, 0xb3, 0x6e, 0x3e,
	0x99, 0x34, 0x34, 0xf2, 0xc3, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xc3, 0xb9, 0x14, 0xd0,
	0x17, 0x00, 0x00,
}
