package milvusctl

import (
	"context"

	"github.com/milvus-io/birdwatcher/framework"
	"github.com/milvus-io/birdwatcher/internal/ops"
)

// -----------------------------------------------------------------------------
// insert

type InsertParam struct {
	framework.ParamBase `use:"insert" desc:"insert rows generated by --gen specs"`
	Collection          string   `name:"collection" default:"" desc:"collection name"`
	Partition           string   `name:"partition" default:"" desc:"optional partition name"`
	Gen                 []string `name:"gen" desc:"column generator: field=gen_type:key=value:... (repeatable)"`
}

func (s *MilvusctlState) InsertCommand(ctx context.Context, p *InsertParam) error {
	cols, err := parseGenSpecs(p.Gen)
	if err != nil {
		return err
	}
	return s.executeOp(ctx, &ops.InsertParams{Collection: p.Collection, Partition: p.Partition, Columns: cols})
}

// -----------------------------------------------------------------------------
// upsert

type UpsertParam struct {
	framework.ParamBase `use:"upsert" desc:"upsert rows generated by --gen specs"`
	Collection          string   `name:"collection" default:"" desc:"collection name"`
	Partition           string   `name:"partition" default:"" desc:"optional partition name"`
	Gen                 []string `name:"gen" desc:"column generator: field=gen_type:key=value:..."`
	Partial             bool     `name:"partial" default:"false" desc:"partial update"`
}

func (s *MilvusctlState) UpsertCommand(ctx context.Context, p *UpsertParam) error {
	cols, err := parseGenSpecs(p.Gen)
	if err != nil {
		return err
	}
	return s.executeOp(ctx, &ops.UpsertParams{Collection: p.Collection, Partition: p.Partition, Columns: cols, PartialUpdate: p.Partial})
}

// -----------------------------------------------------------------------------
// delete

type DeleteParam struct {
	framework.ParamBase `use:"delete" desc:"delete rows by filter expression or primary-key IDs"`
	Collection          string   `name:"collection" default:"" desc:"collection name"`
	Partition           string   `name:"partition" default:"" desc:"optional partition name"`
	Filter              string   `name:"filter" default:"" desc:"expression like \"id >= 10\""`
	PKField             string   `name:"pk-field" default:"" desc:"primary key field name (needed with --int64-ids or --string-ids)"`
	Int64IDs            []int64  `name:"int64-ids" desc:"list of int64 ids to delete"`
	StringIDs           []string `name:"string-ids" desc:"list of string ids to delete"`
}

func (s *MilvusctlState) DeleteCommand(ctx context.Context, p *DeleteParam) error {
	return s.executeOp(ctx, &ops.DeleteParams{
		Collection: p.Collection, Partition: p.Partition,
		Filter: p.Filter, PKField: p.PKField,
		Int64IDs: p.Int64IDs, StringIDs: p.StringIDs,
	})
}
