// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/birdwatcher/proto/v2.2/commonpb"
	internalpb "github.com/milvus-io/birdwatcher/proto/v2.2/internalpb"
	milvuspb "github.com/milvus-io/birdwatcher/proto/v2.2/milvuspb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvalidateCollMetaCacheRequest struct {
	// MsgType:
	//
	//	DropCollection    ->  {meta cache, dml channels}
	//	Other             ->  {meta cache}
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CollectionID         int64             `protobuf:"varint,4,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionName        string            `protobuf:"bytes,5,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvalidateCollMetaCacheRequest) Reset()         { *m = InvalidateCollMetaCacheRequest{} }
func (m *InvalidateCollMetaCacheRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidateCollMetaCacheRequest) ProtoMessage()    {}
func (*InvalidateCollMetaCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *InvalidateCollMetaCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateCollMetaCacheRequest.Unmarshal(m, b)
}
func (m *InvalidateCollMetaCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateCollMetaCacheRequest.Marshal(b, m, deterministic)
}
func (m *InvalidateCollMetaCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateCollMetaCacheRequest.Merge(m, src)
}
func (m *InvalidateCollMetaCacheRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidateCollMetaCacheRequest.Size(m)
}
func (m *InvalidateCollMetaCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateCollMetaCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateCollMetaCacheRequest proto.InternalMessageInfo

func (m *InvalidateCollMetaCacheRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *InvalidateCollMetaCacheRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *InvalidateCollMetaCacheRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *InvalidateCollMetaCacheRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *InvalidateCollMetaCacheRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

type InvalidateShardLeaderCacheRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionIDs        []int64           `protobuf:"varint,2,rep,packed,name=collectionIDs,proto3" json:"collectionIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvalidateShardLeaderCacheRequest) Reset()         { *m = InvalidateShardLeaderCacheRequest{} }
func (m *InvalidateShardLeaderCacheRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidateShardLeaderCacheRequest) ProtoMessage()    {}
func (*InvalidateShardLeaderCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *InvalidateShardLeaderCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateShardLeaderCacheRequest.Unmarshal(m, b)
}
func (m *InvalidateShardLeaderCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateShardLeaderCacheRequest.Marshal(b, m, deterministic)
}
func (m *InvalidateShardLeaderCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateShardLeaderCacheRequest.Merge(m, src)
}
func (m *InvalidateShardLeaderCacheRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidateShardLeaderCacheRequest.Size(m)
}
func (m *InvalidateShardLeaderCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateShardLeaderCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateShardLeaderCacheRequest proto.InternalMessageInfo

func (m *InvalidateShardLeaderCacheRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *InvalidateShardLeaderCacheRequest) GetCollectionIDs() []int64 {
	if m != nil {
		return m.CollectionIDs
	}
	return nil
}

type InvalidateCredCacheRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvalidateCredCacheRequest) Reset()         { *m = InvalidateCredCacheRequest{} }
func (m *InvalidateCredCacheRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidateCredCacheRequest) ProtoMessage()    {}
func (*InvalidateCredCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *InvalidateCredCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateCredCacheRequest.Unmarshal(m, b)
}
func (m *InvalidateCredCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateCredCacheRequest.Marshal(b, m, deterministic)
}
func (m *InvalidateCredCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateCredCacheRequest.Merge(m, src)
}
func (m *InvalidateCredCacheRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidateCredCacheRequest.Size(m)
}
func (m *InvalidateCredCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateCredCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateCredCacheRequest proto.InternalMessageInfo

func (m *InvalidateCredCacheRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *InvalidateCredCacheRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UpdateCredCacheRequest struct {
	Base     *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Username string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// password stored in cache
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCredCacheRequest) Reset()         { *m = UpdateCredCacheRequest{} }
func (m *UpdateCredCacheRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCredCacheRequest) ProtoMessage()    {}
func (*UpdateCredCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *UpdateCredCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCredCacheRequest.Unmarshal(m, b)
}
func (m *UpdateCredCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCredCacheRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCredCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCredCacheRequest.Merge(m, src)
}
func (m *UpdateCredCacheRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCredCacheRequest.Size(m)
}
func (m *UpdateCredCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCredCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCredCacheRequest proto.InternalMessageInfo

func (m *UpdateCredCacheRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UpdateCredCacheRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateCredCacheRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RefreshPolicyInfoCacheRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OpType               int32             `protobuf:"varint,2,opt,name=opType,proto3" json:"opType,omitempty"`
	OpKey                string            `protobuf:"bytes,3,opt,name=opKey,proto3" json:"opKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RefreshPolicyInfoCacheRequest) Reset()         { *m = RefreshPolicyInfoCacheRequest{} }
func (m *RefreshPolicyInfoCacheRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshPolicyInfoCacheRequest) ProtoMessage()    {}
func (*RefreshPolicyInfoCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *RefreshPolicyInfoCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshPolicyInfoCacheRequest.Unmarshal(m, b)
}
func (m *RefreshPolicyInfoCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshPolicyInfoCacheRequest.Marshal(b, m, deterministic)
}
func (m *RefreshPolicyInfoCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshPolicyInfoCacheRequest.Merge(m, src)
}
func (m *RefreshPolicyInfoCacheRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshPolicyInfoCacheRequest.Size(m)
}
func (m *RefreshPolicyInfoCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshPolicyInfoCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshPolicyInfoCacheRequest proto.InternalMessageInfo

func (m *RefreshPolicyInfoCacheRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RefreshPolicyInfoCacheRequest) GetOpType() int32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

func (m *RefreshPolicyInfoCacheRequest) GetOpKey() string {
	if m != nil {
		return m.OpKey
	}
	return ""
}

// Deprecated: use ClusterLimiter instead it
type CollectionRate struct {
	Collection           int64                 `protobuf:"varint,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Rates                []*internalpb.Rate    `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	States               []milvuspb.QuotaState `protobuf:"varint,3,rep,packed,name=states,proto3,enum=milvus.protov2.milvus.QuotaState" json:"states,omitempty"`
	Codes                []commonpb.ErrorCode  `protobuf:"varint,4,rep,packed,name=codes,proto3,enum=milvus.protov2.common.ErrorCode" json:"codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CollectionRate) Reset()         { *m = CollectionRate{} }
func (m *CollectionRate) String() string { return proto.CompactTextString(m) }
func (*CollectionRate) ProtoMessage()    {}
func (*CollectionRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *CollectionRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionRate.Unmarshal(m, b)
}
func (m *CollectionRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionRate.Marshal(b, m, deterministic)
}
func (m *CollectionRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionRate.Merge(m, src)
}
func (m *CollectionRate) XXX_Size() int {
	return xxx_messageInfo_CollectionRate.Size(m)
}
func (m *CollectionRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionRate.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionRate proto.InternalMessageInfo

func (m *CollectionRate) GetCollection() int64 {
	if m != nil {
		return m.Collection
	}
	return 0
}

func (m *CollectionRate) GetRates() []*internalpb.Rate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *CollectionRate) GetStates() []milvuspb.QuotaState {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *CollectionRate) GetCodes() []commonpb.ErrorCode {
	if m != nil {
		return m.Codes
	}
	return nil
}

type LimiterNode struct {
	// self limiter information
	Limiter *Limiter `protobuf:"bytes,1,opt,name=limiter,proto3" json:"limiter,omitempty"`
	// db id -> db limiter
	// collection id -> collection limiter
	// partition id -> partition limiter
	Children             map[int64]*LimiterNode `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LimiterNode) Reset()         { *m = LimiterNode{} }
func (m *LimiterNode) String() string { return proto.CompactTextString(m) }
func (*LimiterNode) ProtoMessage()    {}
func (*LimiterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *LimiterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimiterNode.Unmarshal(m, b)
}
func (m *LimiterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimiterNode.Marshal(b, m, deterministic)
}
func (m *LimiterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimiterNode.Merge(m, src)
}
func (m *LimiterNode) XXX_Size() int {
	return xxx_messageInfo_LimiterNode.Size(m)
}
func (m *LimiterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_LimiterNode.DiscardUnknown(m)
}

var xxx_messageInfo_LimiterNode proto.InternalMessageInfo

func (m *LimiterNode) GetLimiter() *Limiter {
	if m != nil {
		return m.Limiter
	}
	return nil
}

func (m *LimiterNode) GetChildren() map[int64]*LimiterNode {
	if m != nil {
		return m.Children
	}
	return nil
}

type Limiter struct {
	Rates []*internalpb.Rate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	// we can use map to store quota states and error code, because key in map fields cannot be enum types
	States               []milvuspb.QuotaState `protobuf:"varint,2,rep,packed,name=states,proto3,enum=milvus.protov2.milvus.QuotaState" json:"states,omitempty"`
	Codes                []commonpb.ErrorCode  `protobuf:"varint,3,rep,packed,name=codes,proto3,enum=milvus.protov2.common.ErrorCode" json:"codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Limiter) Reset()         { *m = Limiter{} }
func (m *Limiter) String() string { return proto.CompactTextString(m) }
func (*Limiter) ProtoMessage()    {}
func (*Limiter) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *Limiter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limiter.Unmarshal(m, b)
}
func (m *Limiter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limiter.Marshal(b, m, deterministic)
}
func (m *Limiter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limiter.Merge(m, src)
}
func (m *Limiter) XXX_Size() int {
	return xxx_messageInfo_Limiter.Size(m)
}
func (m *Limiter) XXX_DiscardUnknown() {
	xxx_messageInfo_Limiter.DiscardUnknown(m)
}

var xxx_messageInfo_Limiter proto.InternalMessageInfo

func (m *Limiter) GetRates() []*internalpb.Rate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *Limiter) GetStates() []milvuspb.QuotaState {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *Limiter) GetCodes() []commonpb.ErrorCode {
	if m != nil {
		return m.Codes
	}
	return nil
}

type SetRatesRequest struct {
	Base *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// deprecated
	Rates                []*CollectionRate `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	RootLimiter          *LimiterNode      `protobuf:"bytes,3,opt,name=rootLimiter,proto3" json:"rootLimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetRatesRequest) Reset()         { *m = SetRatesRequest{} }
func (m *SetRatesRequest) String() string { return proto.CompactTextString(m) }
func (*SetRatesRequest) ProtoMessage()    {}
func (*SetRatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *SetRatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRatesRequest.Unmarshal(m, b)
}
func (m *SetRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRatesRequest.Marshal(b, m, deterministic)
}
func (m *SetRatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRatesRequest.Merge(m, src)
}
func (m *SetRatesRequest) XXX_Size() int {
	return xxx_messageInfo_SetRatesRequest.Size(m)
}
func (m *SetRatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRatesRequest proto.InternalMessageInfo

func (m *SetRatesRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SetRatesRequest) GetRates() []*CollectionRate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *SetRatesRequest) GetRootLimiter() *LimiterNode {
	if m != nil {
		return m.RootLimiter
	}
	return nil
}

type ListClientInfosRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListClientInfosRequest) Reset()         { *m = ListClientInfosRequest{} }
func (m *ListClientInfosRequest) String() string { return proto.CompactTextString(m) }
func (*ListClientInfosRequest) ProtoMessage()    {}
func (*ListClientInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{9}
}

func (m *ListClientInfosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientInfosRequest.Unmarshal(m, b)
}
func (m *ListClientInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientInfosRequest.Marshal(b, m, deterministic)
}
func (m *ListClientInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientInfosRequest.Merge(m, src)
}
func (m *ListClientInfosRequest) XXX_Size() int {
	return xxx_messageInfo_ListClientInfosRequest.Size(m)
}
func (m *ListClientInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientInfosRequest proto.InternalMessageInfo

func (m *ListClientInfosRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

type ListClientInfosResponse struct {
	Status               *commonpb.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClientInfos          []*commonpb.ClientInfo `protobuf:"bytes,2,rep,name=client_infos,json=clientInfos,proto3" json:"client_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListClientInfosResponse) Reset()         { *m = ListClientInfosResponse{} }
func (m *ListClientInfosResponse) String() string { return proto.CompactTextString(m) }
func (*ListClientInfosResponse) ProtoMessage()    {}
func (*ListClientInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{10}
}

func (m *ListClientInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientInfosResponse.Unmarshal(m, b)
}
func (m *ListClientInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientInfosResponse.Marshal(b, m, deterministic)
}
func (m *ListClientInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientInfosResponse.Merge(m, src)
}
func (m *ListClientInfosResponse) XXX_Size() int {
	return xxx_messageInfo_ListClientInfosResponse.Size(m)
}
func (m *ListClientInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientInfosResponse proto.InternalMessageInfo

func (m *ListClientInfosResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListClientInfosResponse) GetClientInfos() []*commonpb.ClientInfo {
	if m != nil {
		return m.ClientInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*InvalidateCollMetaCacheRequest)(nil), "milvus.protov2.proxy.InvalidateCollMetaCacheRequest")
	proto.RegisterType((*InvalidateShardLeaderCacheRequest)(nil), "milvus.protov2.proxy.InvalidateShardLeaderCacheRequest")
	proto.RegisterType((*InvalidateCredCacheRequest)(nil), "milvus.protov2.proxy.InvalidateCredCacheRequest")
	proto.RegisterType((*UpdateCredCacheRequest)(nil), "milvus.protov2.proxy.UpdateCredCacheRequest")
	proto.RegisterType((*RefreshPolicyInfoCacheRequest)(nil), "milvus.protov2.proxy.RefreshPolicyInfoCacheRequest")
	proto.RegisterType((*CollectionRate)(nil), "milvus.protov2.proxy.CollectionRate")
	proto.RegisterType((*LimiterNode)(nil), "milvus.protov2.proxy.LimiterNode")
	proto.RegisterMapType((map[int64]*LimiterNode)(nil), "milvus.protov2.proxy.LimiterNode.ChildrenEntry")
	proto.RegisterType((*Limiter)(nil), "milvus.protov2.proxy.Limiter")
	proto.RegisterType((*SetRatesRequest)(nil), "milvus.protov2.proxy.SetRatesRequest")
	proto.RegisterType((*ListClientInfosRequest)(nil), "milvus.protov2.proxy.ListClientInfosRequest")
	proto.RegisterType((*ListClientInfosResponse)(nil), "milvus.protov2.proxy.ListClientInfosResponse")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 998 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xcf, 0xc6, 0x71, 0x92, 0xff, 0xb1, 0x93, 0xfc, 0x19, 0x85, 0xd4, 0x58, 0x4a, 0xe4, 0xac,
	0x9a, 0xd6, 0x88, 0x34, 0x2e, 0x4e, 0x21, 0xd0, 0xcb, 0x3a, 0x95, 0x15, 0x35, 0xa9, 0xc2, 0x1a,
	0xb8, 0x40, 0x82, 0x6a, 0xbd, 0x7b, 0x12, 0x0f, 0xac, 0x67, 0x96, 0x99, 0xb1, 0xc1, 0x12, 0x5c,
	0x20, 0x71, 0xc1, 0x13, 0xf0, 0x1e, 0xbc, 0x04, 0xcf, 0xc0, 0x2d, 0xcf, 0xc0, 0x0b, 0xa0, 0xdd,
	0x99, 0x5d, 0x7f, 0xae, 0x9d, 0xd4, 0x12, 0x77, 0x73, 0xce, 0xfc, 0xce, 0xf9, 0x9d, 0xaf, 0xf9,
	0x80, 0x42, 0x28, 0xf8, 0x8f, 0x83, 0x93, 0x50, 0x70, 0xc5, 0xc9, 0x6e, 0x97, 0x06, 0xfd, 0x9e,
	0xd4, 0x52, 0xbf, 0x7e, 0x12, 0xef, 0x95, 0x8b, 0x1e, 0xef, 0x76, 0x39, 0xd3, 0xda, 0xf2, 0x36,
	0x65, 0x0a, 0x05, 0x73, 0x03, 0x23, 0x17, 0x47, 0x6d, 0xec, 0xbf, 0x2d, 0x38, 0xb8, 0x60, 0x7d,
	0x37, 0xa0, 0xbe, 0xab, 0xb0, 0xc1, 0x83, 0xe0, 0x0a, 0x95, 0xdb, 0x70, 0xbd, 0x0e, 0x3a, 0xf8,
	0x7d, 0x0f, 0xa5, 0x22, 0x75, 0x58, 0x6b, 0xbb, 0x12, 0x4b, 0x56, 0xc5, 0xaa, 0x16, 0xea, 0x07,
	0x27, 0x13, 0x9c, 0x86, 0xec, 0x4a, 0xde, 0xbe, 0x70, 0x25, 0x3a, 0x31, 0x96, 0x3c, 0x80, 0x0d,
	0xbf, 0xfd, 0x86, 0xb9, 0x5d, 0x2c, 0xad, 0x56, 0xac, 0xea, 0xff, 0x9c, 0x75, 0xbf, 0xfd, 0xda,
	0xed, 0x22, 0x79, 0x0c, 0x3b, 0x1e, 0x0f, 0x02, 0xf4, 0x14, 0xe5, 0x4c, 0x03, 0x72, 0x31, 0x60,
	0x7b, 0xa8, 0x8e, 0x81, 0x36, 0x14, 0x87, 0x9a, 0x8b, 0xf3, 0xd2, 0x5a, 0xc5, 0xaa, 0xe6, 0x9c,
	0x31, 0x1d, 0x39, 0x82, 0xed, 0xd0, 0x15, 0x8a, 0x0e, 0x7d, 0xe5, 0x63, 0x5f, 0x5b, 0xa9, 0x36,
	0x72, 0x65, 0xff, 0x0c, 0x87, 0xc3, 0x14, 0x5b, 0x1d, 0x57, 0xf8, 0x97, 0xe8, 0xfa, 0x28, 0x96,
	0xce, 0xf2, 0x21, 0x6c, 0x8d, 0xc6, 0x23, 0x4b, 0xab, 0x95, 0x5c, 0x35, 0xe7, 0x8c, 0x2b, 0xed,
	0x00, 0xca, 0x23, 0x15, 0x16, 0xe8, 0x2f, 0xcd, 0x5b, 0x86, 0xcd, 0x9e, 0x8c, 0x7a, 0x9a, 0x96,
	0x37, 0x95, 0xed, 0x5f, 0x2d, 0xd8, 0xfb, 0x22, 0xfc, 0x2f, 0xa8, 0xa2, 0xbd, 0xd0, 0x95, 0xf2,
	0x07, 0x2e, 0x7c, 0xd3, 0xc4, 0x54, 0xb6, 0x7f, 0xb1, 0x60, 0xdf, 0xc1, 0x1b, 0x81, 0xb2, 0x73,
	0xcd, 0x03, 0xea, 0x0d, 0x2e, 0xd8, 0x0d, 0x5f, 0x3a, 0x9a, 0x3d, 0x58, 0xe7, 0xe1, 0xe7, 0x83,
	0x50, 0xc7, 0x92, 0x77, 0x8c, 0x44, 0x76, 0x21, 0xcf, 0xc3, 0x57, 0x38, 0x30, 0x61, 0x68, 0xc1,
	0xfe, 0xcb, 0x82, 0xed, 0x46, 0xda, 0x0a, 0xc7, 0x55, 0x48, 0x0e, 0x00, 0x86, 0xcd, 0x89, 0xa9,
	0x73, 0xce, 0x88, 0x86, 0x9c, 0x42, 0x5e, 0xb8, 0x0a, 0x75, 0x27, 0x0b, 0xf5, 0xfd, 0xc9, 0xa8,
	0xd2, 0xb3, 0x14, 0x79, 0x73, 0x34, 0x96, 0x7c, 0x0a, 0xeb, 0x52, 0xc5, 0x56, 0xb9, 0x4a, 0xae,
	0xba, 0x5d, 0x3f, 0x9c, 0xb4, 0x32, 0xe2, 0x67, 0x3d, 0xae, 0xdc, 0x56, 0x84, 0x74, 0x8c, 0x01,
	0xf9, 0x18, 0xf2, 0x1e, 0xf7, 0x51, 0x96, 0xd6, 0x62, 0xcb, 0x4a, 0x46, 0x15, 0x5e, 0x0a, 0xc1,
	0x45, 0x83, 0xfb, 0xe8, 0x68, 0xb8, 0xfd, 0x8f, 0x05, 0x85, 0x4b, 0xda, 0xa5, 0x0a, 0xc5, 0x6b,
	0xee, 0x23, 0x39, 0x83, 0x8d, 0x40, 0x8b, 0xa6, 0x9e, 0x53, 0x91, 0xeb, 0x6b, 0xc3, 0xd8, 0x38,
	0x09, 0x9a, 0xbc, 0x82, 0x4d, 0xaf, 0x43, 0x03, 0x5f, 0x20, 0x33, 0x39, 0xd7, 0xe6, 0x5a, 0x46,
	0x6c, 0x27, 0x0d, 0x63, 0xf1, 0x92, 0x29, 0x31, 0x70, 0x52, 0x07, 0xe5, 0x6f, 0x60, 0x6b, 0x6c,
	0x8b, 0xfc, 0x1f, 0x72, 0xdf, 0xe1, 0xc0, 0xd4, 0x39, 0x5a, 0x92, 0x33, 0xc8, 0xf7, 0xdd, 0xa0,
	0xa7, 0x1b, 0x58, 0x98, 0x2e, 0xd5, 0x14, 0x99, 0xa3, 0xf1, 0xcf, 0x57, 0x3f, 0xb1, 0xec, 0x3f,
	0x2c, 0xd8, 0x30, 0x5b, 0xc3, 0x4e, 0x59, 0x6f, 0xd5, 0xa9, 0xd5, 0xb7, 0xee, 0x54, 0xee, 0x7e,
	0x9d, 0xfa, 0xd3, 0x82, 0x9d, 0x16, 0xaa, 0x28, 0x0a, 0xb9, 0xcc, 0xe8, 0x3f, 0x1f, 0x9f, 0xcc,
	0x87, 0xb3, 0x0b, 0x37, 0x3e, 0xee, 0x49, 0xda, 0x0d, 0x28, 0x08, 0xce, 0x95, 0x29, 0x5d, 0x7c,
	0x48, 0xee, 0x54, 0xfa, 0x51, 0x2b, 0xfb, 0x12, 0xf6, 0x2e, 0xa9, 0x54, 0x8d, 0x80, 0x22, 0x53,
	0xd1, 0x69, 0x5e, 0x26, 0x1d, 0xfb, 0x77, 0x0b, 0x1e, 0x4c, 0xb9, 0x93, 0x21, 0x67, 0x12, 0xc9,
	0x47, 0xba, 0x4b, 0x3d, 0x99, 0x35, 0xcb, 0xc6, 0x63, 0x2b, 0x06, 0x39, 0x06, 0x4c, 0xce, 0xa1,
	0xe8, 0xc5, 0xde, 0xde, 0xd0, 0xc8, 0x9d, 0x29, 0xd4, 0x61, 0x86, 0xf1, 0x90, 0xd8, 0x29, 0x78,
	0xc3, 0x20, 0xea, 0xbf, 0x15, 0x21, 0x7f, 0x1d, 0x55, 0x82, 0x84, 0x40, 0x9a, 0xa8, 0x1a, 0xbc,
	0x1b, 0x72, 0x86, 0x4c, 0xb5, 0xf4, 0x1c, 0x3c, 0xcd, 0x18, 0x99, 0x69, 0xa8, 0x29, 0x4f, 0xf9,
	0x51, 0x86, 0xc5, 0x04, 0xdc, 0x5e, 0x21, 0x3d, 0xd8, 0x6d, 0x62, 0x2c, 0x52, 0xa9, 0xa8, 0x27,
	0x1b, 0x1d, 0x97, 0x31, 0x0c, 0xc8, 0xb3, 0xcc, 0xe1, 0x9e, 0x05, 0x4f, 0x78, 0x8f, 0x32, 0x78,
	0x5b, 0x4a, 0x50, 0x76, 0x9b, 0x54, 0xdb, 0x5e, 0x21, 0x7d, 0xd8, 0x1f, 0xff, 0x02, 0xe8, 0x09,
	0x4a, 0x3f, 0x02, 0xd3, 0xfc, 0x7a, 0x54, 0xe6, 0xff, 0x1b, 0xca, 0xf3, 0xdb, 0x66, 0xaf, 0x10,
	0x84, 0x62, 0x13, 0xd5, 0xb9, 0x9f, 0xa4, 0x79, 0x3c, 0x2f, 0xcd, 0x14, 0x76, 0xef, 0xf4, 0x18,
	0xbc, 0x37, 0xfe, 0xfe, 0x22, 0x53, 0xd4, 0x0d, 0x74, 0x6a, 0x4f, 0x17, 0xa6, 0x36, 0xf1, 0x8a,
	0x2e, 0x4e, 0xeb, 0x06, 0xde, 0x1d, 0x3e, 0xc0, 0xa3, 0x5c, 0xc7, 0xb3, 0xb9, 0x66, 0xbf, 0xd6,
	0x8b, 0x79, 0x18, 0xec, 0xcd, 0x7e, 0x61, 0xc9, 0xe9, 0x6c, 0xa2, 0xb9, 0xef, 0xf1, 0x62, 0xbe,
	0x0e, 0xec, 0x34, 0x51, 0xc5, 0x67, 0xe3, 0x0a, 0x95, 0xa0, 0x9e, 0x24, 0xd5, 0xec, 0xc3, 0x60,
	0x20, 0x89, 0xf7, 0xf7, 0xef, 0x80, 0x4c, 0x3b, 0xe6, 0xc0, 0x66, 0x72, 0x65, 0x92, 0xa3, 0xd9,
	0xb9, 0x4c, 0x5c, 0xa9, 0x8b, 0xa3, 0x0f, 0x61, 0x67, 0xe2, 0xbe, 0xc9, 0xea, 0xc7, 0xec, 0x5b,
	0xae, 0xfc, 0xe4, 0x8e, 0xe8, 0x34, 0x8b, 0xaf, 0x61, 0xf3, 0xa2, 0x1b, 0x72, 0xa1, 0xbe, 0xac,
	0x93, 0x47, 0x99, 0xa3, 0xad, 0x21, 0x09, 0xc9, 0xe3, 0x85, 0xb8, 0xd4, 0xfd, 0x4f, 0xf0, 0x4e,
	0x13, 0x95, 0x56, 0x5f, 0x0b, 0x7e, 0x2b, 0x50, 0x4a, 0xf2, 0xe1, 0xbc, 0x23, 0x34, 0x8e, 0x4d,
	0x28, 0xeb, 0xf7, 0x31, 0x49, 0xd9, 0xbf, 0x8d, 0xfe, 0x1f, 0xd2, 0xec, 0x4b, 0xf2, 0x41, 0xa6,
	0x93, 0x11, 0x54, 0xc2, 0x78, 0x7c, 0x37, 0xf0, 0xc8, 0xfd, 0x54, 0xce, 0xfe, 0xbf, 0x93, 0xb3,
	0x45, 0x27, 0x38, 0xe3, 0xc7, 0xbf, 0x70, 0x64, 0x5e, 0x3c, 0xfb, 0xaa, 0x7e, 0x4b, 0x55, 0xa7,
	0xd7, 0x8e, 0x76, 0x6a, 0x1a, 0xfc, 0x84, 0x72, 0xb3, 0xaa, 0x25, 0x51, 0xd7, 0x62, 0xfb, 0x5a,
	0x4c, 0x1b, 0xb6, 0xdb, 0xeb, 0xb1, 0x78, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xa1,
	0x32, 0x28, 0xa9, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	GetComponentStates(ctx context.Context, in *milvuspb.GetComponentStatesRequest, opts ...grpc.CallOption) (*milvuspb.ComponentStates, error)
	GetStatisticsChannel(ctx context.Context, in *internalpb.GetStatisticsChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error)
	InvalidateCollectionMetaCache(ctx context.Context, in *InvalidateCollMetaCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	GetDdChannel(ctx context.Context, in *internalpb.GetDdChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error)
	InvalidateCredentialCache(ctx context.Context, in *InvalidateCredCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	UpdateCredentialCache(ctx context.Context, in *UpdateCredCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	RefreshPolicyInfoCache(ctx context.Context, in *RefreshPolicyInfoCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	GetProxyMetrics(ctx context.Context, in *milvuspb.GetMetricsRequest, opts ...grpc.CallOption) (*milvuspb.GetMetricsResponse, error)
	SetRates(ctx context.Context, in *SetRatesRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
	ListClientInfos(ctx context.Context, in *ListClientInfosRequest, opts ...grpc.CallOption) (*ListClientInfosResponse, error)
	// importV2
	ImportV2(ctx context.Context, in *internalpb.ImportRequest, opts ...grpc.CallOption) (*internalpb.ImportResponse, error)
	GetImportProgress(ctx context.Context, in *internalpb.GetImportProgressRequest, opts ...grpc.CallOption) (*internalpb.GetImportProgressResponse, error)
	ListImports(ctx context.Context, in *internalpb.ListImportsRequest, opts ...grpc.CallOption) (*internalpb.ListImportsResponse, error)
	InvalidateShardLeaderCache(ctx context.Context, in *InvalidateShardLeaderCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) GetComponentStates(ctx context.Context, in *milvuspb.GetComponentStatesRequest, opts ...grpc.CallOption) (*milvuspb.ComponentStates, error) {
	out := new(milvuspb.ComponentStates)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/GetComponentStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetStatisticsChannel(ctx context.Context, in *internalpb.GetStatisticsChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error) {
	out := new(milvuspb.StringResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/GetStatisticsChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) InvalidateCollectionMetaCache(ctx context.Context, in *InvalidateCollMetaCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/InvalidateCollectionMetaCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetDdChannel(ctx context.Context, in *internalpb.GetDdChannelRequest, opts ...grpc.CallOption) (*milvuspb.StringResponse, error) {
	out := new(milvuspb.StringResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/GetDdChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) InvalidateCredentialCache(ctx context.Context, in *InvalidateCredCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/InvalidateCredentialCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) UpdateCredentialCache(ctx context.Context, in *UpdateCredCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/UpdateCredentialCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) RefreshPolicyInfoCache(ctx context.Context, in *RefreshPolicyInfoCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/RefreshPolicyInfoCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetProxyMetrics(ctx context.Context, in *milvuspb.GetMetricsRequest, opts ...grpc.CallOption) (*milvuspb.GetMetricsResponse, error) {
	out := new(milvuspb.GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/GetProxyMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) SetRates(ctx context.Context, in *SetRatesRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/SetRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) ListClientInfos(ctx context.Context, in *ListClientInfosRequest, opts ...grpc.CallOption) (*ListClientInfosResponse, error) {
	out := new(ListClientInfosResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/ListClientInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) ImportV2(ctx context.Context, in *internalpb.ImportRequest, opts ...grpc.CallOption) (*internalpb.ImportResponse, error) {
	out := new(internalpb.ImportResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/ImportV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) GetImportProgress(ctx context.Context, in *internalpb.GetImportProgressRequest, opts ...grpc.CallOption) (*internalpb.GetImportProgressResponse, error) {
	out := new(internalpb.GetImportProgressResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/GetImportProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) ListImports(ctx context.Context, in *internalpb.ListImportsRequest, opts ...grpc.CallOption) (*internalpb.ListImportsResponse, error) {
	out := new(internalpb.ListImportsResponse)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/ListImports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) InvalidateShardLeaderCache(ctx context.Context, in *InvalidateShardLeaderCacheRequest, opts ...grpc.CallOption) (*commonpb.Status, error) {
	out := new(commonpb.Status)
	err := c.cc.Invoke(ctx, "/milvus.protov2.proxy.Proxy/InvalidateShardLeaderCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	GetComponentStates(context.Context, *milvuspb.GetComponentStatesRequest) (*milvuspb.ComponentStates, error)
	GetStatisticsChannel(context.Context, *internalpb.GetStatisticsChannelRequest) (*milvuspb.StringResponse, error)
	InvalidateCollectionMetaCache(context.Context, *InvalidateCollMetaCacheRequest) (*commonpb.Status, error)
	GetDdChannel(context.Context, *internalpb.GetDdChannelRequest) (*milvuspb.StringResponse, error)
	InvalidateCredentialCache(context.Context, *InvalidateCredCacheRequest) (*commonpb.Status, error)
	UpdateCredentialCache(context.Context, *UpdateCredCacheRequest) (*commonpb.Status, error)
	RefreshPolicyInfoCache(context.Context, *RefreshPolicyInfoCacheRequest) (*commonpb.Status, error)
	GetProxyMetrics(context.Context, *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error)
	SetRates(context.Context, *SetRatesRequest) (*commonpb.Status, error)
	ListClientInfos(context.Context, *ListClientInfosRequest) (*ListClientInfosResponse, error)
	// importV2
	ImportV2(context.Context, *internalpb.ImportRequest) (*internalpb.ImportResponse, error)
	GetImportProgress(context.Context, *internalpb.GetImportProgressRequest) (*internalpb.GetImportProgressResponse, error)
	ListImports(context.Context, *internalpb.ListImportsRequest) (*internalpb.ListImportsResponse, error)
	InvalidateShardLeaderCache(context.Context, *InvalidateShardLeaderCacheRequest) (*commonpb.Status, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) GetComponentStates(ctx context.Context, req *milvuspb.GetComponentStatesRequest) (*milvuspb.ComponentStates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentStates not implemented")
}
func (*UnimplementedProxyServer) GetStatisticsChannel(ctx context.Context, req *internalpb.GetStatisticsChannelRequest) (*milvuspb.StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsChannel not implemented")
}
func (*UnimplementedProxyServer) InvalidateCollectionMetaCache(ctx context.Context, req *InvalidateCollMetaCacheRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateCollectionMetaCache not implemented")
}
func (*UnimplementedProxyServer) GetDdChannel(ctx context.Context, req *internalpb.GetDdChannelRequest) (*milvuspb.StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDdChannel not implemented")
}
func (*UnimplementedProxyServer) InvalidateCredentialCache(ctx context.Context, req *InvalidateCredCacheRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateCredentialCache not implemented")
}
func (*UnimplementedProxyServer) UpdateCredentialCache(ctx context.Context, req *UpdateCredCacheRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentialCache not implemented")
}
func (*UnimplementedProxyServer) RefreshPolicyInfoCache(ctx context.Context, req *RefreshPolicyInfoCacheRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshPolicyInfoCache not implemented")
}
func (*UnimplementedProxyServer) GetProxyMetrics(ctx context.Context, req *milvuspb.GetMetricsRequest) (*milvuspb.GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProxyMetrics not implemented")
}
func (*UnimplementedProxyServer) SetRates(ctx context.Context, req *SetRatesRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRates not implemented")
}
func (*UnimplementedProxyServer) ListClientInfos(ctx context.Context, req *ListClientInfosRequest) (*ListClientInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClientInfos not implemented")
}
func (*UnimplementedProxyServer) ImportV2(ctx context.Context, req *internalpb.ImportRequest) (*internalpb.ImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportV2 not implemented")
}
func (*UnimplementedProxyServer) GetImportProgress(ctx context.Context, req *internalpb.GetImportProgressRequest) (*internalpb.GetImportProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImportProgress not implemented")
}
func (*UnimplementedProxyServer) ListImports(ctx context.Context, req *internalpb.ListImportsRequest) (*internalpb.ListImportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImports not implemented")
}
func (*UnimplementedProxyServer) InvalidateShardLeaderCache(ctx context.Context, req *InvalidateShardLeaderCacheRequest) (*commonpb.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateShardLeaderCache not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_GetComponentStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.GetComponentStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetComponentStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/GetComponentStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetComponentStates(ctx, req.(*milvuspb.GetComponentStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetStatisticsChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetStatisticsChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetStatisticsChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/GetStatisticsChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetStatisticsChannel(ctx, req.(*internalpb.GetStatisticsChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_InvalidateCollectionMetaCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateCollMetaCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).InvalidateCollectionMetaCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/InvalidateCollectionMetaCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).InvalidateCollectionMetaCache(ctx, req.(*InvalidateCollMetaCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetDdChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetDdChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetDdChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/GetDdChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetDdChannel(ctx, req.(*internalpb.GetDdChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_InvalidateCredentialCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateCredCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).InvalidateCredentialCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/InvalidateCredentialCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).InvalidateCredentialCache(ctx, req.(*InvalidateCredCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_UpdateCredentialCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).UpdateCredentialCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/UpdateCredentialCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).UpdateCredentialCache(ctx, req.(*UpdateCredCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_RefreshPolicyInfoCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshPolicyInfoCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).RefreshPolicyInfoCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/RefreshPolicyInfoCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).RefreshPolicyInfoCache(ctx, req.(*RefreshPolicyInfoCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetProxyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(milvuspb.GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetProxyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/GetProxyMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetProxyMetrics(ctx, req.(*milvuspb.GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_SetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).SetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/SetRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).SetRates(ctx, req.(*SetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_ListClientInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).ListClientInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/ListClientInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).ListClientInfos(ctx, req.(*ListClientInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_ImportV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).ImportV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/ImportV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).ImportV2(ctx, req.(*internalpb.ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_GetImportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.GetImportProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).GetImportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/GetImportProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).GetImportProgress(ctx, req.(*internalpb.GetImportProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_ListImports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(internalpb.ListImportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).ListImports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/ListImports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).ListImports(ctx, req.(*internalpb.ListImportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_InvalidateShardLeaderCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateShardLeaderCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).InvalidateShardLeaderCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.protov2.proxy.Proxy/InvalidateShardLeaderCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).InvalidateShardLeaderCache(ctx, req.(*InvalidateShardLeaderCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.protov2.proxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComponentStates",
			Handler:    _Proxy_GetComponentStates_Handler,
		},
		{
			MethodName: "GetStatisticsChannel",
			Handler:    _Proxy_GetStatisticsChannel_Handler,
		},
		{
			MethodName: "InvalidateCollectionMetaCache",
			Handler:    _Proxy_InvalidateCollectionMetaCache_Handler,
		},
		{
			MethodName: "GetDdChannel",
			Handler:    _Proxy_GetDdChannel_Handler,
		},
		{
			MethodName: "InvalidateCredentialCache",
			Handler:    _Proxy_InvalidateCredentialCache_Handler,
		},
		{
			MethodName: "UpdateCredentialCache",
			Handler:    _Proxy_UpdateCredentialCache_Handler,
		},
		{
			MethodName: "RefreshPolicyInfoCache",
			Handler:    _Proxy_RefreshPolicyInfoCache_Handler,
		},
		{
			MethodName: "GetProxyMetrics",
			Handler:    _Proxy_GetProxyMetrics_Handler,
		},
		{
			MethodName: "SetRates",
			Handler:    _Proxy_SetRates_Handler,
		},
		{
			MethodName: "ListClientInfos",
			Handler:    _Proxy_ListClientInfos_Handler,
		},
		{
			MethodName: "ImportV2",
			Handler:    _Proxy_ImportV2_Handler,
		},
		{
			MethodName: "GetImportProgress",
			Handler:    _Proxy_GetImportProgress_Handler,
		},
		{
			MethodName: "ListImports",
			Handler:    _Proxy_ListImports_Handler,
		},
		{
			MethodName: "InvalidateShardLeaderCache",
			Handler:    _Proxy_InvalidateShardLeaderCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
