// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditOpType int32

const (
	AuditOpType_AuditOpNone AuditOpType = 0
	AuditOpType_OpDel       AuditOpType = 1
	AuditOpType_OpPut       AuditOpType = 2
	AuditOpType_OpPutBefore AuditOpType = 3
	AuditOpType_OpPutAfter  AuditOpType = 4
)

// Enum value maps for AuditOpType.
var (
	AuditOpType_name = map[int32]string{
		0: "AuditOpNone",
		1: "OpDel",
		2: "OpPut",
		3: "OpPutBefore",
		4: "OpPutAfter",
	}
	AuditOpType_value = map[string]int32{
		"AuditOpNone": 0,
		"OpDel":       1,
		"OpPut":       2,
		"OpPutBefore": 3,
		"OpPutAfter":  4,
	}
)

func (x AuditOpType) Enum() *AuditOpType {
	p := new(AuditOpType)
	*p = x
	return p
}

func (x AuditOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (AuditOpType) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x AuditOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditOpType.Descriptor instead.
func (AuditOpType) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

type PartType int32

const (
	PartType_PartTypeNone         PartType = 0
	PartType_EtcdBackup           PartType = 1
	PartType_MetricsBackup        PartType = 2
	PartType_MetricsDefaultBackup PartType = 3
	PartType_Configurations       PartType = 4
	PartType_AppMetrics           PartType = 5
	PartType_LoadedSegments       PartType = 6
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PartTypeNone",
		1: "EtcdBackup",
		2: "MetricsBackup",
		3: "MetricsDefaultBackup",
		4: "Configurations",
		5: "AppMetrics",
		6: "LoadedSegments",
	}
	PartType_value = map[string]int32{
		"PartTypeNone":         0,
		"EtcdBackup":           1,
		"MetricsBackup":        2,
		"MetricsDefaultBackup": 3,
		"Configurations":       4,
		"AppMetrics":           5,
		"LoadedSegments":       6,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[1].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[1]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

type AuditHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	OpType     int32 `protobuf:"varint,2,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	EntriesNum int32 `protobuf:"varint,3,opt,name=entries_num,json=entriesNum,proto3" json:"entries_num,omitempty"`
}

func (x *AuditHeader) Reset() {
	*x = AuditHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditHeader) ProtoMessage() {}

func (x *AuditHeader) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditHeader.ProtoReflect.Descriptor instead.
func (*AuditHeader) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *AuditHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AuditHeader) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *AuditHeader) GetEntriesNum() int32 {
	if x != nil {
		return x.EntriesNum
	}
	return 0
}

type BackupHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Instance  string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	MetaPath  string `protobuf:"bytes,3,opt,name=meta_path,json=metaPath,proto3" json:"meta_path,omitempty"`
	Entries   int64  `protobuf:"varint,4,opt,name=entries,proto3" json:"entries,omitempty"`
	Component string `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Extra     []byte `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *BackupHeader) Reset() {
	*x = BackupHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHeader) ProtoMessage() {}

func (x *BackupHeader) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHeader.ProtoReflect.Descriptor instead.
func (*BackupHeader) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *BackupHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupHeader) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *BackupHeader) GetMetaPath() string {
	if x != nil {
		return x.MetaPath
	}
	return ""
}

func (x *BackupHeader) GetEntries() int64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *BackupHeader) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *BackupHeader) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PartHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartType PartType `protobuf:"varint,1,opt,name=part_type,json=partType,proto3,enum=milvus.proto.birdwatcher.PartType" json:"part_type,omitempty"`
	PartLen  int64    `protobuf:"varint,2,opt,name=part_len,json=partLen,proto3" json:"part_len,omitempty"`
	Extra    []byte   `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *PartHeader) Reset() {
	*x = PartHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartHeader) ProtoMessage() {}

func (x *PartHeader) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartHeader.ProtoReflect.Descriptor instead.
func (*PartHeader) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *PartHeader) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PartTypeNone
}

func (x *PartHeader) GetPartLen() int64 {
	if x != nil {
		return x.PartLen
	}
	return 0
}

func (x *PartHeader) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type WorkspaceMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Instance string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	MetaPath string `protobuf:"bytes,3,opt,name=meta_path,json=metaPath,proto3" json:"meta_path,omitempty"`
}

func (x *WorkspaceMeta) Reset() {
	*x = WorkspaceMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMeta) ProtoMessage() {}

func (x *WorkspaceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMeta.ProtoReflect.Descriptor instead.
func (*WorkspaceMeta) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkspaceMeta) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *WorkspaceMeta) GetMetaPath() string {
	if x != nil {
		return x.MetaPath
	}
	return ""
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x69, 0x72, 0x64,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x7e, 0x0a, 0x0a,
	0x50, 0x61, 0x72, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x70, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70,
	0x61, 0x72, 0x74, 0x4c, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x62, 0x0a, 0x0d,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68,
	0x2a, 0x55, 0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x74, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x74, 0x4f, 0x70, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x70, 0x44, 0x65, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4f,
	0x70, 0x50, 0x75, 0x74, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x70, 0x50, 0x75, 0x74, 0x42,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x70, 0x50, 0x75, 0x74,
	0x41, 0x66, 0x74, 0x65, 0x72, 0x10, 0x04, 0x2a, 0x91, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x74, 0x63, 0x64, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x10, 0x06, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73,
	0x2d, 0x69, 0x6f, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_proto_goTypes = []interface{}{
	(AuditOpType)(0),      // 0: milvus.proto.birdwatcher.AuditOpType
	(PartType)(0),         // 1: milvus.proto.birdwatcher.PartType
	(*AuditHeader)(nil),   // 2: milvus.proto.birdwatcher.AuditHeader
	(*BackupHeader)(nil),  // 3: milvus.proto.birdwatcher.BackupHeader
	(*PartHeader)(nil),    // 4: milvus.proto.birdwatcher.PartHeader
	(*WorkspaceMeta)(nil), // 5: milvus.proto.birdwatcher.WorkspaceMeta
}
var file_model_proto_depIdxs = []int32{
	1, // 0: milvus.proto.birdwatcher.PartHeader.part_type:type_name -> milvus.proto.birdwatcher.PartType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuditHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
